### ISSUE TITLE
mysql_fetch_row_format Error.

### ISSUE THREAD

**Issue by hidrodf** [pBlueG/SA-MP-MySQL#101]
Hello! I am updating a FS to a new version but I have a trouble with something:
`public OnQueryFinish( query[], resultid, extraid, connectionHandle ) {
	if(resultid == 1) {
	    new resultline[128], data[11][128];
		while(mysql_fetch_row_format(resultline,"|"))`

mysql_fetch_row_format does not exist. Anyone knows something about this?

Thanks!

**Comment by IstuntmanI** [comment]
http://forum.sa-mp.com/showthread.php?t=337810 (this tutorial is a bit outdated, but still)
http://wiki.sa-mp.com/wiki/MySQL/R33
