### ISSUE TITLE
UTF8 Turkish Bug

### ISSUE THREAD

**Issue by MaxAndolini** [pBlueG/SA-MP-MySQL#102]
I am use CHARSET=utf8 COLLATE=utf8_turkish_ci;

No problem in phpmyadmin but when get data 

Original:

Los Santos Polis Departmanı

without mysql_set_charset("utf8");

Los Santos Polis Departman?

with mysql_set_charset("utf8");

Los Santos Polis DepartmanÄ±

Please help me

**Comment by MySQLMaster** [comment]
Hi Max I solve problem but I need a few minutes please

**Comment by MaxAndolini** [comment]
Ok I am wait :+1:

**Comment by MySQLMaster** [comment]
Tamam ercan anladım zamqi

**Comment by MySQLMaster** [comment]
I haven't solve a problem because I don't find problem on the query sorry , lucky job !

**Comment by IstuntmanI** [comment]
https://github.com/pBlueG/SA-MP-MySQL/issues/97

**Comment by MaxAndolini** [comment]
I am already look at but I could not figure

**Comment by MaxAndolini** [comment]
I am use latin5 and fixed.
