### ISSUE TITLE
Failed (libmysqlclient.so.18: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by pekkahacker** [pBlueG/SA-MP-MySQL#103]
my sql error

**Comment by maddinat0r** [comment]
Read the FAQ.

**Comment by pekkahacker** [comment]
where is faq

**Comment by Jeroen52** [comment]
@pekkahacker https://github.com/pBlueG/SA-MP-MySQL#faq

**Comment by GabrielLins64** [comment]
The error used to persist even if I had the mysql client lib installed, but for anyone having this issue on Linux distros, I could fix it by using the 'debian-static' package instead 'debian'.
