### ISSUE TITLE
SQL queries being stored in memory

### ISSUE THREAD

**Issue by frostgaming** [pBlueG/SA-MP-MySQL#106]
Hello

I have been trying to debug why my server memory has been going up every day and tracking down memory leaks. (It's at 800MB usage atm)

I dumped all of the server memory with [GDB](https://www.gnu.org/software/gdb/) (from /proc/PID/maps) and the largest file was 400MB (which is half of the entire processes usage), inside I found tons of `SELECT`, `UPDATE`, and other statements handled by the MySQL plugin.  -d3 is off, so there is no reason it should be writing all of the SQL queries to memory.

```
root@eu [~/dumps]# strings 16157-09336000-2146e000.dump | grep -E 'SELECT|UPDATE' | wc -l
```
125381

The file contained 125,381 lines of `SELECT`/`UPDATE` queries. I saw queries that usually run during login, independent queries which are ran via commands, and everything else in between. Why are these being written to memory and being kept there permanently?  This is causing the memory usage to increase daily as more queries are ran by users.

Is this expected behavior from the plugin, or is there something possibly in the gamemode that could cause this? (For reference, -d3 is disabled on compilation, I also tried disabling my other plugins such as crashdetect, and it did not have any effect.)

Let me know if there's something obvious I'm missing that would cause this.

**Comment by maddinat0r** [comment]
It seems like you've got a lot of MySQL cached results in memory. Are you using `cache_save` or `mysql_query` anywhere? If you don't destroy the caches through `cache_delete`, they'll just stay in memory forever.

**Comment by frostgaming** [comment]
I do use mysql_query, but I always clear it using cache_delete on every instance of those, these should not be in memory.

**Comment by maddinat0r** [comment]
What version is your MySQL plugin on? Are there any errors/warnings in your `mysql_log.txt`?

**Comment by frostgaming** [comment]
R39-5

There is one warning in the log repeated every few minutes:
[WARNING] cache_get_field_content_int - no active cache

Although some of the MySQL queries that appeared in the dump would not generate that warning.

**Comment by maddinat0r** [comment]
Code like this can cause that warning:
```pawn
new Cache:cache = mysql_query(sql, "SELECT stuff");
res = cache_get_field_content_int(0, "field1");
cache_delete(cache);
res2 = cache_get_field_content_int(0, "field2"); //this causes a "no active cache" warning
```
Please make sure that you fix those warnings, as they could indicate that you somewhere misplaced a `cache_delete` or overridden a cache with another, e.g.
```pawn
new Cache:cache = mysql_query(sql, "SELECT * FROM table_a");
val1 = cache_get_field_content_int(0, "field1");

new Cache:cache2 = mysql_query(sql, "SELECT * FROM table_b");
val 2 = cache_get_field_content_int(0, "field1");
cache_delete(cache2);

val3 = cache_get_field_content_int(0, "field2"); //no active cache warning
cache_delete(cache);
```

**Comment by frostgaming** [comment]
I had thought of that, but some of the queries that are saving to memory are using mysql_pquery, so that should not apply.

**Comment by maddinat0r** [comment]
The query string itself is stored in the cache and you can retrieve it through `cache_get_query_string`. And even if every one of your queries stored in memory would be 1000 characters long, it wouldn't fill up 400MB (125381 * 1000 = 125.4 * 10^6).

Could you also do the following?

1. Enable debug logging
2. Run your server for a while to pile up memory leaks
3. Force-kill the server (so that it won't shut down properly)
4. Open the MySQL log file
5. Count the occurrences of `CMySQLResult::CMySQLResult()`
6. Count the occurrences of `CMySQLResult::~CMySQLResult()`
7. Share your results here

**Comment by maddinat0r** [comment]
@frostgaming any updates on this?

**Comment by frostgaming** [comment]
This issue was found to be related to d3. Closing this.
