### ISSUE TITLE
Incompatible to MariaDB

### ISSUE THREAD

**Issue by BirknerAlex** [pBlueG/SA-MP-MySQL#109]
The Plugin does not work with MariaDB 10. I've tried to compile it by my own but I always fail too:

```
root@server:/opt/SA-MP-MySQL# make
[ 12%] Built target fmt
[ 28%] Built target amx
[ 44%] Built target log-core
Linking CXX shared module mysql.so
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../libmysqlclient_r.so when searching for -lmysqlclient_r
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../libmysqlclient_r.a when searching for -lmysqlclient_r
/usr/bin/ld: skipping incompatible //usr/lib/libmysqlclient_r.so when searching for -lmysqlclient_r
/usr/bin/ld: skipping incompatible //usr/lib/libmysqlclient_r.a when searching for -lmysqlclient_r
/usr/bin/ld: cannot find -lmysqlclient_r
collect2: error: ld returned 1 exit status
make[2]: *** [src/mysql.so] Error 1
make[1]: *** [src/CMakeFiles/mysql.dir/all] Error 2
make: *** [all] Error 2
```

Seems like it does not support it with the different libmysqlclient from MariaDB.

**Comment by Jeroen52** [comment]
Are you using a specific distro? I could try to compile it on a VM on my PC.

**Comment by maddinat0r** [comment]
You're using 64bit libraries. Download the 32bit MariaDB connector library.

**Comment by BirknerAlex** [comment]
@Jeroen52 I am using Ubuntu 14.04 LTS 64bit with the official MariaDB 10 repository. 

@maddinat0r I will try it again later this evening. But it sounds legit. Thanks!

**Comment by BirknerAlex** [comment]
Hello,

@maddinat0r that was the reason, I didn't saw the notice also in your README. Compiled it with 32bit libs, works fine now :)

Thanks!
