### ISSUE TITLE
suggestion mysql_error

### ISSUE THREAD

**Issue by Dayvison** [pBlueG/SA-MP-MySQL#110]
Simple [mysql_error](http://php.net/manual/pt_BR/function.mysql-error.php) function.

```pawn
native mysql_error(dest[], MySQL:handle = MYSQL_DEFAULT_HANDLE, size = sizeof dest);
```

Why not :+1:

**Comment by maddinat0r** [comment]
I actually wanted to create that function already in R40, but I kinda forgot about it. I'll add it in R41.

**Comment by Dayvison** [comment]
wow so fast. Really thanks
