### ISSUE TITLE
Bad Entry Point?

### ISSUE THREAD

**Issue by xFirez** [pBlueG/SA-MP-MySQL#111]
In my server log I get this error:
```[03:34:53]   Loaded.
[03:34:53]  Loading plugin: mysql.so
[03:34:53]  >> plugin.mysql: R40 successfully loaded.
[03:34:53]   Loaded.```

After all the loading it says:
```[03:34:53] [debug] Run time error 20: "Invalid index parameter (bad entry point)"```

Now after looking for it on the sa-mp forums it's nothing to do with my "main"
```
main()
{
	print("\n====================================");
	print("|         Test |");
	print("====================================\n");
	return 1;
}```

**Comment by WopsS** [comment]
Hello,

Do you have the last version of **crash-detect**?

**Comment by xFirez** [comment]
@WopsS 

Yes I do. I even re-uploaded it to my server and I still get the same issue. Never happened when I was on 39-6. Now since I upgraded to R40, it returns this error. I am speaking with Madd in personal messages.

**Comment by xFirez** [comment]
Resolved by removing crashdetect.

**Comment by maddinat0r** [comment]
Just linking the YSI issue here for future reference: Misiur/YSI-Includes#121
