### ISSUE TITLE
Char arrays not working in cache_get_value_name functions.

### ISSUE THREAD

**Issue by TommyB123** [pBlueG/SA-MP-MySQL#112]
This line of code

```pawn
cache_get_value_name_bool(i, "Locked", Locked{x});
```

gives me this error

`C:\Users\TommyB\Desktop\servers\redcountyrp\gamemodes\RCRP_MySQL.pwn(68974) : error 035: argument type mismatch (argument 3)`

Not sure if there's anything I can try to fix it on my end or if I'm doing anything wrong, but any help would be appreciated.

**Comment by maddinat0r** [comment]
Packed strings are not supported by the MySQL plugin, so there's not much you can do there. You'll have to use normal, unpacked strings.

**Comment by maddinat0r** [comment]
Additionally, you can't pass single packed characters per reference, only full cells. This is a PAWN limitation.
