### ISSUE TITLE
Opened curly brace crashes the server.

### ISSUE THREAD

**Issue by Konstantinos-Sk** [pBlueG/SA-MP-MySQL#115]
The character **{** crashes the server when trying to retrieve it with both _cache_get_value_name_ and _cache_get_value_index_, this didn't happen when R40 was at 84%

**Comment by Jeroen52** [comment]
I am not sure which commit it is, but if you know which commit it was you could try to bisect the issue.

**Comment by Konstantinos-Sk** [comment]
It seems I had tried that character when I was testing ORM but not cache. I went way way back and up to  [this point](https://ci.appveyor.com/project/maddinat0r/sa-mp-mysql/build/52) it retrieves the character fine. In the next build [(53)](https://ci.appveyor.com/project/maddinat0r/sa-mp-mysql/build/53) this issue appears. Looking at the commits, there are 6 more without a built and from the name the most suspicious is [this commit](https://github.com/pBlueG/SA-MP-MySQL/commit/48f48710ec5b1557ac859dd19000c0d139cefdfe)
