### ISSUE TITLE
Log Crash

### ISSUE THREAD

**Issue by MaxAndolini** [pBlueG/SA-MP-MySQL#116]
> [23:39:59] [debug] Server crashed while executing Mod.amx
> [23:39:59] [debug] AMX backtrace:
> [23:39:59] [debug] #0 native cache_get_value_name () from mysql.DLL
> [23:39:59] [debug] #1 006e0c5c in public LoadGangs () at Mod.pwn:57755
> [23:39:59] [debug] Native backtrace:
> [23:39:59] [debug] #0 77d2ddf7 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
> [23:39:59] [debug] #1 77d0136f in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
> [23:39:59] [debug] #2 6cca49a5 in ?? () from C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
> [23:39:59] [debug] #3 6bdb9fab in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #4 6bdb9b2e in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #5 6bdba71f in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #6 6bdb9c7a in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #7 6bdb39f7 in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #8 6bdbf6d5 in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #9 6bdcfbd0 in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #10 6bdd3541 in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #11 004010b6 in ?? () from samp-server.exe
> [23:39:59] [debug] #12 6cb6c6fa in ?? () from plugins\crashdetect.DLL
> [23:39:59] [debug] #13 6cb72278 in ?? () from plugins\crashdetect.DLL
> [23:39:59] [debug] #14 6cb6a0d7 in ?? () from plugins\crashdetect.DLL
> [23:39:59] [debug] #15 6cb6c74a in ?? () from plugins\crashdetect.DLL
> [23:39:59] [debug] #16 6bd64509 in ?? () from plugins\streamer.DLL
> [23:39:59] [debug] #17 6bdb8682 in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #18 6bdd0f83 in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #19 6bdd1ffc in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #20 6bdbcc61 in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #21 6bdbce53 in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #22 6bdbe7fe in ?? () from plugins\mysql.DLL
> [23:39:59] [debug] #23 00469a66 in ?? () from samp-server.exe
> [23:39:59] [debug] #24 0048d4db in ?? () from samp-server.exe
> [23:39:59] [debug] #25 0049b4a1 in ?? () from samp-server.exe
> [23:39:59] [debug] #26 0049b4b1 in ?? () from samp-server.exe

errors.log

> [23:39:55] [log-core] exception 0XE06D7363 (<unknown>) from Unhandled Exception Handler catched; shutting log-core down

Therefore crash:

mysql_log(ERROR | WARNING);

**Comment by WopsS** [comment]
Hello,

I think you should post **mysql.log** from plugins folder.

**Comment by maddinat0r** [comment]
You're probably experiencing #115. Try disabling logging completely (`mysql_log(NONE);`) and see if it still crashes.

**Comment by MaxAndolini** [comment]
I delete this line no problem mysql_log(ERROR | WARNING);

But solve this please.

**Comment by maddinat0r** [comment]
Already fixed in f3509f45706d9a2025637f78b703564d0c0987ab. R41 will include this fix.
