### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MaxAndolini** [pBlueG/SA-MP-MySQL#117]
[01:39:00] [plugins/mysql] mysql_format: can't escape string '(nullptr)' (RPG\pawno\include\easy-mysql.inc:1918)
[01:39:00] [plugins/mysql] cache_get_value_name_int: invalid row index '0' (number of rows: '0') (RPG\pawno\include\easy-mysql.inc:707)

https://github.com/MaxAndolini/easy-mysql/blob/master/easy-mysql.inc

**Comment by Konstantinos-Sk** [comment]
Do you use the exact same code as the code in the link? The lines do not match.

Anyway, about the first: the string you try to escape is empty.
About the second: There are no rows but you try to retrieve the data.

**Comment by MaxAndolini** [comment]
Uptaded.

**Comment by Konstantinos-Sk** [comment]
Add:
```
if(!value[0]) return 0;
```
to prevent having an empty string which obviously can't be escaped.

---

_cache_get_row_count_ now returns 0/1 for failure/success. So either:
```
cache_get_row_count(count)
if (count) cache_get_value_name_int(0, field, int);
cache_delete(result);
```
or
```
if (cache_num_rows()) cache_get_value_name_int(0, field, int);
cache_delete(result);
```

**Comment by MaxAndolini** [comment]
I will try. Thank you.

**Comment by maddinat0r** [comment]
Escaping an empty string through `mysql_format` should work (and probably print a warning), so that's a bug.

**Comment by MaxAndolini** [comment]
Fixed. Thank you.
