### ISSUE TITLE
Bringing back OnQueryFinish

### ISSUE THREAD

**Issue by D-o-n** [pBlueG/SA-MP-MySQL#118]
Okay so since I noticed this callback has been removed, I'm here to suggest it back again.
It's really a good Develop/debug tool, and I would love to have it while developing.
If there isn't one anymore it would be awesome if we could use mysql_option(QUERY_FINISH_CALLBACK, true)
and have OnQueryFinish get called for me it'd be just exec time logging during development so I wouldn't just having that instead of OnQueryFinish but I find that too useful, if not possible just put the execute time in logs when such option is enabled.

I doubt it would be a really hard thing to add, and it doesn't put much pressure since the default would be off.

**Comment by maddinat0r** [comment]
Why would you manually want to measure the time when there's `cache_get_query_exec_time`? You do realize there is a notable overhead when timing yourself and you would probably __never__ get timing results as exact as through that native?
You could also hook `mysql_tquery` and always force it to call a fixed callback and pass the actual callback as parameter (and call it through `CallLocalFunction`). This way you'd have your own custom `OnQueryFinish` callback and you could simply activate it through the preprocessor (`#ifdef DEVELOPMENT ... #endif`) whenever you need it.

I should also add the query timing to the info log whenever a query is executed. It was there in R33+, but I kinda forgot to add it back again in R40.

**Comment by D-o-n** [comment]
> Why would you manually want to measure the time when there's cache_get_query_exec_time? You do realize there is a notable overhead when timing yourself and you would probably never get timing results as exact as through that native?
Thats actually my point, I want to use that function on threaded queries I haven't specified a callback to, It seems too unreasonable to just add callback to every single one of those during development and remove them when compiling code for the server.
my custom OnQueryFinish would break the auto cache remove system wouldn't it?

And also yeah, adding that query timing to logs would be sufficient enough for me tho.

**Comment by spmn** [comment]
> my custom OnQueryFinish would break the auto cache deleting system wouldn't it?

It shouldn't.

**Comment by maddinat0r** [comment]
The active cache from a result callback is automatically deleted when that result callback returns.
```pawn
mysql_tquery(sql, "SELECT 123", "Callback");

public Callback()
{
    //query result callback, there is an active cache
    CallLocalFunction("MyFunc", "");
    NormalFunc();
    return 1;
}

public MyFunc()
{
    //we also have here access to the active cache, 
    //because we've been called from the result callback
    assert(cache_num_rows() == 1);
    return 1;
}

NormalFunc()
{
    //the same applies to non-public functions too of course
    assert(cache_num_fields() == 1);
    return 1;
}
```

**Comment by D-o-n** [comment]
Well okay then, I guess I'll make that custom callback, although I guess you'll re-add the query exec time to logs, right? then probably only gonna use the callback until R41.
