### ISSUE TITLE
Static Version

### ISSUE THREAD

**Issue by KrYpToDeN** [pBlueG/SA-MP-MySQL#119]
Hello.

Could you do static version for R40, please?
Can't run it on Centos 6 x86_64

**Comment by Dayvison** [comment]
CentOS 6 not suported by r40.


Q: I get a version GLIBCXX_3.4.15' not found error (or similar). How can I solve this?
A: Update your system. If that still didn't work, you'll need to upgrade your Linux distribution to a version which provides the gcc 4.8 (or higher) compiler. For example, if you're on CentOS 6, which only has gcc 4.4, you'll need to upgrade to CentOS 7.

**Comment by KrYpToDeN** [comment]
Ok. I need Centos 7_amd64 or x86_64?

**Comment by Dayvison** [comment]
I think anyone works.

**Comment by Jeroen52** [comment]
If you're using CentOS 6 you could also stick with R39-6.

**Comment by KrYpToDeN** [comment]
I'm going to install Centos 7. What's the better for SA:MP server and this plugin?
Centos 7_amd64 or x86_64?

**Comment by Jeroen52** [comment]
@KrYpToDeN I think that this might give more information on the naming convention. https://en.wikipedia.org/wiki/X86-64#Industry_naming_conventions

**Comment by KrYpToDeN** [comment]
Thanks to all of you! 

Question to pBlueG, With the help of which version OS(Centos 7_amd64 or x86_64) plugin R40 was compiled?

**Comment by Dayvison** [comment]
pBlueG not developer this anymore, you should ask to maddinat0r about this plugin, but the compiled version of plugins sa-mp it is always x86 because sa-mp no supports the x64 every build you can see `-m32`.


If have erros in my english, sorry.

**Comment by maddinat0r** [comment]
As @Dayvison said, all SA-MP plugins are 32bit libraries.
And in this context, amd64 and x86_64 are the same thing.

**Comment by KrYpToDeN** [comment]
Ok, @maddinat0r, Thanks.

Could you help me, please with starting.

I use Centos 7 x86_64, your plugin for Centos. And i got this:
[08:57:41]  Loading plugin: mysql.so
[08:57:41]   Failed (libmysqlclient.so.18: cannot open shared object file: No such file or directory)

What command should i use to do it?
