### ISSUE TITLE
Continue last theme with starting plugin

### ISSUE THREAD

**Issue by KrYpToDeN** [pBlueG/SA-MP-MySQL#121]
Could you help me, please, with starting.

I use Centos 7 x86_64, your this plugin(R41) for Centos. And i got this:
[08:57:41]  Loading plugin: mysql.so
[08:57:41]   Failed (libmysqlclient.so.18: cannot open shared object file: No such file or directory)

What command should i use to do it?

**Comment by maddinat0r** [comment]
`yum install mariadb-libs.i686`

**Comment by KrYpToDeN** [comment]
@maddinat0r i did it and i got:
Package 1:mariadb-libs-5.5.50-1.el7_2.i686 is obsoleted by mysql-community-libs-compat-5.7.15-1.el7.x86_64 which is already installed
Nothing to do

**Comment by KrYpToDeN** [comment]
Thank you very much.
I uninstall mysql-libs and did what you said.

The problem was solved.

**Comment by IstuntmanI** [comment]
This kind of problems should be posted in the official forum thread, not here, as it isn't an issue with the plugin.

**Comment by KrYpToDeN** [comment]
@IstuntmanI Ok, i understood you.
Next time it will be OK.
