### ISSUE TITLE
[ERROR] cache_get_value_index: invalid row ('x') or field ('x') index

### ISSUE THREAD

**Issue by audriuslio** [pBlueG/SA-MP-MySQL#122]
When getting this error. No printing in what querie this was, and too will be good if it's will by printed in what callback with all parameters with error happin.

**Comment by maddinat0r** [comment]
Recompile your script with debug symbols and the log will show you exactly in which line and file that error happened.

**Comment by audriuslio** [comment]
debug symbols what they are?

**Comment by Konstantinos-Sk** [comment]
Create **pawn.cfg** file into _pawno_ folder. Open the file and write **_-d3_** in it. Open your script and re-compile. 
Done.

**Comment by audriuslio** [comment]
I know that already, but i can't my gamemode too big with compiling in that way. That why i'am creating here issue that i need that creator of this plugin will made more log information, without -d3

**Comment by Dayvison** [comment]
not possible without -d2 or -d3
