### ISSUE TITLE
Assign connectionhandle id to a global variable in a include?

### ISSUE THREAD

**Issue by Zaila** [pBlueG/SA-MP-MySQL#123]
Just tried out some pawn scripting again after a couple of years of hiatus and i've encountered a problem with the latest release of the MySQL plugin.

To explain properly what i'm trying to do, i will show the code first as i'm scripting in several filterscripts instead of a single gamemode.

custom.inc:
```
#include <a_samp>
#include <sscanf2>
#include <a_mysql>
#include <zcmd>
#include <colors>


new MySQL: db_con;
```

database.pwn:
```

#include <custom>

#define MYSQL_HOST "127.0.0.1"
#define MYSQL_USER "root"
#define MYSQL_PASSWORD ""
#define MYSQL_DATABASE "samp"

public OnFilterScriptInit()
{
	print("Loading database script...");

	new MySQLOpt: option_id = mysql_init_options();

	mysql_set_option(option_id, AUTO_RECONNECT, true);
	print("Mysql Connection Auto Reconnect set!");

	db_con = mysql_connect(MYSQL_HOST, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE, option_id);

	if(db_con == MYSQL_INVALID_HANDLE || mysql_errno(db_con) != 0)
	{
		printf("Failed to connect to database: %d", mysql_errno(db_con));
		SendRconCommand("exit");
		return 1;
	}
	printf("Successfully connected to database \"%s\" at \"%s\".", MYSQL_DATABASE, MYSQL_HOST);
	print("Database script loaded.");
	return 1;
}
```

account.pwn:
```

#include <custom>

//===[Callbacks]======================
forward OnPlayerDataLoaded(playerid, race_check);
//====================================

//===[Variables}======================

//====================================

public OnFilterScriptInit()
{
	print("Loading Account script...");

	mysql_format(db_con, s_query, sizeof(s_query), "SELECT * FROM accounts WHERE username = 'test' LIMIT 1");
	mysql_tquery(db_con, s_query, "OnPlayerDataLoaded", "d", 1);

	print("Account script loaded.");
	return 1;
}

public OnPlayerDataLoaded(playerid)
{
	if(cache_num_rows() > 0)
	{
		SendMessageNF(playerid, "Account exist.");
	}
	else
	{
		SendMessageNF(playerid, "Account does not exist.");
	}
	return 1;
}
```

What i'm doing is basically creating a gamemode into several filterscripts instead of just a single gamemode. For this, i'm having a custom include where i'm storing commonly used variables and functions so i dont have to rewrite them into several scripts. In custom.inc, i'm creating 'new MySQL:db_con;' variable for the connection handle. I'm then trying to connect to the database in 'database.pwn" which is working. However, the problems begin in account.pwn which is loaded directly after database.pwn. As you can see, i'm having a query directly into OnFilterScriptInit which i put in after i found this problem for easy debug.

this is the error log produced every time i'm starting the server:

```
[15:40:13] [ERROR] mysql_format: invalid connection handle '0' (D:\SA-MP\filterscripts\account.pwn:17)
[15:40:13] [ERROR] mysql_tquery: invalid connection handle '0' (D:\SA-MP\filterscripts\account.pwn:18)
```

Looks like db_con is not given a proper connection handle ID or is there a problem with having it in a include?

**Comment by Konstantinos-Sk** [comment]
database.pwn and account.pwn are two different filterscripts? If yes, then in account.pwn is by default 0 and you never connect to the mysql server.

If you only have 1 mysql connection, why don't you use MYSQL_DEFAULT_HANDLE?

**Comment by Zaila** [comment]
MYSQL_DEFAULT_HANDLE actually worked great so thanks for that!

I haven't been scripting anything since beginning of 2014 and back then it was possible to just state 1 as connection handle in every script after connecting it so that's what threw me off when trying it now. 

As this wasn't a bug, i'm closing this issue.
