### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MaxAndolini** [pBlueG/SA-MP-MySQL#124]
[13:26:46] [log-core] exception 0XC00000FD (STACK_OVERFLOW) from Vectored Exception Handler catched; shutting log-core down

**Comment by maddinat0r** [comment]
Yes, that's the notification from the log core that it detected a crash and is about to shut down. I can't tell you anything about the actual crash. This also doesn't necessarily mean that the MySQL plugin crashed. So without further information, this is not an issue.
