### ISSUE TITLE
Invalid Row

### ISSUE THREAD

**Issue by MaxAndolini** [pBlueG/SA-MP-MySQL#126]
[16:00:53] [DEBUG] cache_get_value_name_int(26, "atmID", 0x073C68B0)
[16:00:53] [ERROR] cache_get_value_name_int: invalid row index '26' (number of rows: '0')

**Comment by Konstantinos-Sk** [comment]
Do you loop through all the rows? Remember that doing
```
for (new i, j = cache_num_rows(); i <= j; i++)
```
is wrong because row IDs start from 0. The correct would be:
```
for (new i, j = cache_num_rows(); i < j; i++)
```

If that is not the case, find where you are retrieving "atmID" and post some code.

**Comment by MaxAndolini** [comment]
for (new i = 0; i < rows; i ++)

**Comment by maddinat0r** [comment]
As the error message says (` (number of rows: '0')`), there are no rows in your result set.
