### ISSUE TITLE
Mysql R41 for Centos 6 ?

### ISSUE THREAD

**Issue by Abyss-z94** [pBlueG/SA-MP-MySQL#129]
Hi, im using Mysql R41 for my gamemode, but when load on my VPS (Centos 6 64 bit), the plugins can't be loaded for the reason:

[16:08:44]  Loading plugin: mysql.so
[16:08:44]   Failed (libmysqlclient.so.18: cannot open shared object file: No such file or directory)

I were contact my Server support for install libmysqlclient.so.18, but still no work. What i can do now. Please help me !

**Comment by Abyss-z94** [comment]
Nah i were find out Mysql R41 have no longer support CentOS 6. Im gona upgade my VPS now !

**Comment by Jeroen52** [comment]
@Abyss-z94 It is also possible to stick with R39-6, there are still quite a lot of hosts and server admins using CentOS 6 so I am sure it will receive the security updates and bug fixes. It just won't receive the newest and flashiest features that are only compatible with the newer compilers and deps.

Read https://github.com/pBlueG/SA-MP-MySQL/issues/119

I must remind you, code needs to be changed when changed from R39-6 and below to R41.

**Comment by Jeroen52** [comment]
If it is the case that you are upgrading from a version lower than R40 to R40 or higher, I recommend you to read the release notes of R40.
https://github.com/pBlueG/SA-MP-MySQL/releases/tag/R40
