### ISSUE TITLE
mysql_close crash during server /gmx

### ISSUE THREAD

**Issue by JernejL** [pBlueG/SA-MP-MySQL#133]
This is slightly older version of plugin, still this crash is happening for years already, but now i actually have a useable call stack  
 
After rcon /gmx OnGameModeExit calls mysql_close and it always crashes. 
 
backtrace:
#0  0xb7fdd420 in __kernel_vsyscall ()
No symbol table info available.
#1  0xb7fbbd9b in write () from /lib/i386-linux-gnu/libpthread.so.0
No symbol table info available.
#2  0xb785e6cd in vio_write (vio=0x90b4328, buf=0x90cae10 "\001", size=5) at viosocket.c:121
No locals.
#3  0xb785f2a9 in net_real_write (net=0x90b3f60, packet=0x90cae10 "\001", len=5) at net.c:617
        length = 0
        pos = 0x90cae10 "\001"
        end = 0x90cae15 ""
        alarmed = 0 '\000'
        retry_count = 0
        net_blocking = 1 '\001'
#4  0xb785f768 in net_flush (net=0x90b3f60) at net.c:343
        error = 16 '\020'
#5  0xb785f8c4 in net_write_command (net=0x90b3f60, command=1 '\001', header=0x0, head_len=0, packet=0x0, len=0) at net.c:463
        length = <optimized out>
        buff = "\001\000\000\000\001"
        header_size = <optimized out>
#6  0xb785bd95 in cli_advanced_command (mysql=0x90b3f60, command=COM_QUIT, header=0x0, header_length=0, arg=0x0, arg_length=0, skip_check=1 '\001', stmt=0x0) at client.c:804
        result = <optimized out>
#7  0xb7859942 in mysql_close (mysql=0x90b3f60) at client.c:2779
No locals.
#8  0xb78082d9 in CMySQLConnection::Disconnect() () from plugins/mysql_static.so
No symbol table info available.
#9  0xb78225c5 in Native::mysql_close(tagAMX*, int*) () from plugins/mysql_static.so
No symbol table info available.
#10 0x080950e4 in amx_Callback ()
No symbol table info available.
#11 0x08096b85 in amx_Exec ()
No symbol table info available.
#12 0x090aa5c8 in ?? ()
No symbol table info available.
#13 0xb3785d36 in ?? () from plugins/streamer.so
No symbol table info available.
#14 0xb6d14951 in _sampgdk_amxhooks_Exec () from plugins/SampUtils.so
No symbol table info available.
#15 0xb36dd011 in _sampgdk_amxhooks_Exec () from plugins/YSF.so
No symbol table info available.
#16 0x080a4e27 in CGameMode::Unload() ()
No symbol table info available.
#17 0x080abd0d in CNetGame::ShutdownForGameModeRestart() ()
No symbol table info available.
#18 0x080aa20f in main ()
No symbol table info available.

**Comment by maddinat0r** [comment]
Can you create a gdb core dump and email it to me? Which MySQL plugin version are you using? Which MySQL connector library version do you use (libmysql16, libmysql18, ...)? What Linux distribution does this crash happen on?

**Comment by JernejL** [comment]
Sorry, due to the way pawn works, i'm absolutely not submitting a core dump (one could just extract amx from ram and reverse it) 
 
linux is ubuntu, mysql plugin is a older plugin.mysql: R39-3 (because that version doesn't automaticly do multi connection magic that floods and breaks my server with connections)

**Comment by karimcambridge** [comment]
@JernejL 

If your using R39-3, upgrade to R39-4 atleast. I had there same issue ( #64 ).

https://github.com/pBlueG/SA-MP-MySQL/tree/R39-4

I don't see a reason to not use R39-6 though, it's just bug-fixes.

**Comment by maddinat0r** [comment]
I'd also heavily suggest upgrading to R39-6. You don't even have to recompile your script, just replace the plugin file.
I'm also not sure what you mean by
> that version doesn't automaticly do multi connection magic that floods and breaks my server with connections
Care to elaborate?
