### ISSUE TITLE
Hashing the database password and checking.

### ISSUE THREAD

**Issue by Sreyas-Sreelal** [pBlueG/SA-MP-MySQL#134]
I have created an app in c++ to create mysql.ini so as to save my database password hashed (sha256).But the problem is that i cant process it in script because mysql_connect(_) takes plane texts in password arguement. So is there any way to implement this method?

**Comment by maddinat0r** [comment]
No, you have to pass the MySQL account password in plaintext to the MySQL connector.

**Comment by Sreyas-Sreelal** [comment]
Ok then can u implement this feature too in next update?

**Comment by maddinat0r** [comment]
As I said, I need to give the MySQL C API a password in clear-text. So no, I can't implement this. 
You can however change the auth plugin in the client and/or server. Refer to the MySQL documentation for more information.

**Comment by Sreyas-Sreelal** [comment]
Ok thanks for the info :)
