### ISSUE TITLE
No mysql_static

### ISSUE THREAD

**Issue by Sasuke-Uchiha** [pBlueG/SA-MP-MySQL#136]
I hope you can help me here. For the versions before the r41 we had that mysql_static file which is no where to be found.

I tried that Centos7 version it gave me error that you told in FAQ question 2.
Tried installing the libmysqlclient_r.so.18 but the error we had was

` file /usr/lib64/mysql/libmysqlclient.so.18.0.0 from install of compat-mysql55-5.5.45-1.el6.remi.x86_64 conflicts with file from package mariadb-libs-1:5.5.50-1.el7_2.x86_64`

Tried installing with _r and it gave error 
`No package libmysqlclient_r.so.18 available.`

I tried the debian8 static version as it said static in it.
That gave me errors that are in FAQ question 1, but the problem is our gcc is 
`gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)`

So moving on i tried the other file left and it gave the same error.

So one thing you stated that we should use **mysql_static** file which I can't find anywhere in R41-2.

**Comment by Jeroen52** [comment]
Try `yum install mariadb-devel.i686 mariadb-devel.x86_64`

It should provide the following files.
`/usr/lib/mysql/libmysqlclient_r.so`
`/usr/lib64/mysql/libmysqlclient_r.so`

**Comment by Sasuke-Uchiha** [comment]
Thanks this worked!
