### ISSUE TITLE
Crash - MySQL plugin R39-5 - Windows

### ISSUE THREAD

**Issue by Yousha** [pBlueG/SA-MP-MySQL#138]
Is this plugin incompatible with MySQL +5.5 64-bit or 64-bit OS's? it crashes when stopping server...

**Plugin R39-5
MySQL 14.14 Distrib 5.6.26, for Win64 (x86_64)
Using libmysql 5.6.21 (32bit)
Windows 7 Ultimate 64-bit
x64 based system
Installed Ms VC++ Runtime 2010 to 2015 x64 and x86**

`Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	samp-server.exe
  Application Version:	0.3.7.0
  Application Timestamp:	55bccfdf
  Fault Module Name:	mysql.DLL
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	56f7f018
  Exception Code:	c0000005
  Exception Offset:	0000f3b8
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	fbe7
  Additional Information 2:	fbe7be52911a424d2d7a49d357187698
  Additional Information 3:	9d4e
  Additional Information 4:	9d4e8a5ffb0b1e3c7f974b20dc8b577a`

**Comment by maddinat0r** [comment]
Can you update to R39-6, just to be sure this also happens on the latest R39 version? If it still crashes, can you reproduce this crash with full logging enabled (`mysql_log(LOG_ALL)`) and share that log here?

**Comment by Yousha** [comment]
**R39-5 log:**
```
[18:06:21] [DEBUG] mysql_connect - host: "x", user: "x", database: "x", password: "****", port: 3306, autoreconnect: true, pool_size: 2
[18:06:22] [DEBUG] CMySQLHandle::Create - creating new connection..
[18:06:22] [DEBUG] CMySQLHandle::CMySQLHandle - constructor called
[18:06:22] [DEBUG] CMySQLHandle::Create - connection created (id: 1)
[18:06:22] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
[18:06:22] [DEBUG] CMySQLConnection::Connect - connection was successful
[18:06:22] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
[18:06:22] [DEBUG] mysql_errno - connection: 1
[18:06:22] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
[18:06:22] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
[18:06:22] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
[18:06:22] [DEBUG] CMySQLConnection::Connect - connection was successful
[18:06:22] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
[18:06:22] [DEBUG] CMySQLConnection::Connect - connection was successful
[18:06:22] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
[18:06:22] [DEBUG] CMySQLConnection::Connect - connection was successful
[18:06:22] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
[18:06:29] [DEBUG] CMySQLConnection::Disconnect - connection was closed
[18:06:29] [DEBUG] CMySQLConnection::Disconnect - connection was closed
[18:06:29] [DEBUG] CMySQLConnection::Disconnect - connection was closed
[18:06:29] [DEBUG] CMySQLConnection::Disconnect - connection was closed
[18:06:29] [DEBUG] CMySQLHandle::~CMySQLHandle - deconstructor called
```

Updated to 39-6

**R39-6 log:**
```
[18:17:14 02/04/17] [DEBUG] mysql_connect - host: "x", user: "x", database: "x", password: "****", port: 3306, autoreconnect: true, pool_size: 2
[18:17:14 02/04/17] [DEBUG] CMySQLHandle::Create - creating new connection..
[18:17:14 02/04/17] [DEBUG] CMySQLHandle::CMySQLHandle - constructor called
[18:17:14 02/04/17] [DEBUG] CMySQLHandle::Create - connection created (id: 1)
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
[18:17:14 02/04/17] [DEBUG] mysql_errno - connection: 1
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
[18:17:14 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
[18:17:15 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
[18:17:15 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
[18:17:15 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
[18:17:15 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
[18:17:15 02/04/17] [DEBUG] CMySQLHandle::~CMySQLHandle - deconstructor called
```
Still crashes on GM stop.

**Comment by maddinat0r** [comment]
Can you try out this debug build and enable the crashdetect plugin please?
[mysql-R39-6-win32-dbg.zip](https://github.com/pBlueG/SA-MP-MySQL/files/752353/mysql-R39-6-win32-dbg.zip)

**Comment by Yousha** [comment]
Thanks, crashdetect plugin *was already enabled(always):
**My server.cfg**
`plugins crashdetect sscanf streamer mysql whirlpool nativechecker`

And about using that **debug plugin**,  I got these errors:
> The program can't start because MSVCP140D.dll is missing from your computer. Try reinstalling the program to fix this problem.

> [19:18:52]    Error: Function not registered: 'mysql_tquery'
> [19:18:52]    Error: Function not registered: 'cache_get_data'
> [19:18:52]    Error: Function not registered: 'cache_get_field_content_int'
> [19:18:52]    Error: Function not registered: 'cache_get_field_content'
> [19:18:52]    Error: Function not registered: 'cache_insert_id'
> [19:18:52]    Error: Function not registered: 'cache_affected_rows'
> [19:18:52]    Error: Function not registered: 'mysql_escape_string'
> [19:18:52]    Error: Function not registered: 'mysql_log'
> [19:18:52]    Error: Function not registered: 'mysql_connect'
> [19:18:52]    Error: Function not registered: 'mysql_errno'
> [19:18:52] [debug] Run time error 19: "File or function is not found"

Because I dont have **DEBUG version of the CRT files**... so these files are missing in your plugin/package:
**MSVCP140D.dll
VCRUNTIME140D.dll
UCRTBASED.dll**

And I trid to find package of these files but could NOT find anything, so I downloaded them **separately**!
Now by using **32-bit version of those CRT files** Im getting this error:
> The procedure entry point __vcrt_cleanup_type_info_names could not be located in the dynamic link library VCRUNTIME140D.dll

> [19:44:52]    Error: Function not registered: 'mysql_tquery'
> [19:44:52]    Error: Function not registered: 'cache_get_data'
> [19:44:52]    Error: Function not registered: 'cache_get_field_content_int'
> [19:44:52]    Error: Function not registered: 'cache_get_field_content'
> [19:44:52]    Error: Function not registered: 'cache_insert_id'
> [19:44:52]    Error: Function not registered: 'cache_affected_rows'
> [19:44:52]    Error: Function not registered: 'mysql_escape_string'
> [19:44:52]    Error: Function not registered: 'mysql_log'
> [19:44:52]    Error: Function not registered: 'mysql_connect'
> [19:44:52]    Error: Function not registered: 'mysql_errno'
> [19:44:52] [debug] Run time error 19: "File or function is not found"

And by using **64-bit version of those CRT files** Im getting this error:

> [19:44:52]    Error: Function not registered: 'mysql_tquery'
> [19:44:52]    Error: Function not registered: 'cache_get_data'
> [19:44:52]    Error: Function not registered: 'cache_get_field_content_int'
> [19:44:52]    Error: Function not registered: 'cache_get_field_content'
> [19:44:52]    Error: Function not registered: 'cache_insert_id'
> [19:44:52]    Error: Function not registered: 'cache_affected_rows'
> [19:44:52]    Error: Function not registered: 'mysql_escape_string'
> [19:44:52]    Error: Function not registered: 'mysql_log'
> [19:44:52]    Error: Function not registered: 'mysql_connect'
> [19:44:52]    Error: Function not registered: 'mysql_errno'
> [19:44:52] [debug] Run time error 19: "File or function is not found"

**Comment by maddinat0r** [comment]
Ah, sorry, I totally forgot that debug builds depend on the debug runtime (obviously, ha)!
Try out [this DLL](https://github.com/pBlueG/SA-MP-MySQL/files/752452/mysql.zip), that one is compiled statically against the debug runtime.

**Comment by Yousha** [comment]
Same problem, same error and same log:

> [22:39:35 02/04/17] [DEBUG] mysql_connect - host: "x", user: "x", database: "x", password: "****", port: 3306, autoreconnect: true, pool_size: 2
> [22:39:35 02/04/17] [DEBUG] CMySQLHandle::Create - creating new connection..
> [22:39:35 02/04/17] [DEBUG] CMySQLHandle::CMySQLHandle - constructor called
> [22:39:35 02/04/17] [DEBUG] CMySQLHandle::Create - connection created (id: 1)
> [22:39:35 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
> [22:39:35 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
> [22:39:35 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
> [22:39:35 02/04/17] [DEBUG] mysql_errno - connection: 1
> [22:39:35 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
> [22:39:35 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
> [22:39:35 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
> [22:39:36 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
> [22:39:36 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
> [22:39:36 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
> [22:39:36 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
> [22:39:37 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
> [22:39:37 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
> [22:39:38 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
> [22:39:38 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
> [22:39:38 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
> [22:39:38 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
> [22:39:38 02/04/17] [DEBUG] CMySQLHandle::~CMySQLHandle - deconstructor called

EvenViewer:

> Faulting application name: samp-server.exe, version: 0.3.7.0, time stamp: 0x55bccfdf
> Faulting module name: mysql.DLL, version: 0.0.0.0, time stamp: 0x589614f8
> Exception code: 0xc0000005
> Fault offset: 0x0015470f
> Faulting process id: 0x970
> Faulting application start time: 0x01d27f1a38f2b74e
> Faulting application path: D:\Desktop\PAWN\SA-MP\xCnR\samp-server.exe
> Faulting module path: D:\Desktop\PAWN\SA-MP\xCnR\plugins\mysql.DLL
> Report Id: 7a2af6e2-eb0d-11e6-819d-2cd4449d27bf

**Comment by maddinat0r** [comment]
What's really weird is that crashdetect doesn't kick in. Can you try loading MySQL as first, and crashdetect as second plugin?

**Comment by Yousha** [comment]
By loading **mysql** as **SECOND** plugin I have same problem.

By loading **mysql** as **FIRST** plugin problem was solved BUT got this crash log:

**cashinfo.txt**

> SA-MP Server: 0.3.7-R2
> 
> Exception At Address: 0x0048D56F Module: (samp-server.exe)
> 
> Registers:
> EAX: 0xDDDDDDE5	EBX: 0x003E9710	ECX: 0xDDDDDDE5	EDX: 0xDDDDDDDD
> ESI: 0x0018FD40	EDI: 0x0018FD38	EBP: 0x00000000	ESP: 0x0018FE38
> EFLAGS: 0x00010246
> 
> Stack:
> +0000: 0x00000000   0x00001DB1   0x0018FF88   0x7EFDE000
> +0010: 0x0001E000   0x00010101   0x00000023   0x00001E79
> +0020: 0x000000A0   0x00001030   0x003EA790   0x656D6167
> +0030: 0x65646F6D   0x00003531   0x004C4020   0x004C401C
> +0040: 0x7EFDE000   0x004AB4A0   0x0018FE70   0x0018FF78
> +0050: 0x0018FF78   0x0049D208   0x004BA2F8   0xFFFFFFFF
> +0060: 0x0049B4A1   0x0049B4B1   0x004AB4A0   0x0018FF78
> +0070: 0x004AB0E1   0xFFFFFFFF   0x0049CCA6   0x00000001
> +0080: 0x003E18B0   0x003E18D0   0x00000094   0x00000006
> +0090: 0x00000001   0x00001DB1   0x00000002   0x76726553
> +00A0: 0x20656369   0x6B636150   0x00003120   0x00000000
> +00B0: 0x00000000   0x00000000   0x00000000   0x00000000
> +00C0: 0x00000000   0x00000000   0x00000000   0x00000000
> +00D0: 0x00000000   0x00000000   0x00000000   0x00000000
> +00E0: 0x00000000   0x00000000   0x00000000   0x00000000
> +00F0: 0x00000000   0x00000000   0x00000000   0x00000000
> +0100: 0x00000000   0x00000000   0x00000000   0x00000000
> +0110: 0x00000000   0x00000000   0x0049CB52   0x00000000
> +0120: 0x00000000   0x7EFDE000   0x00000000   0x00000000
> +0130: 0xC0000005   0x00000000   0x0018FEC0   0x0018F6AC
> 
> --------------------------
> 
> Loaded Modules:
> samp-server.exe	A: 0x00400000 - 0x00519000	(D:\Desktop\PAWN\SA-MP\BLCnR\samp-server.exe)
> ntdll.dll	A: 0x771B0000 - 0x77330000	(C:\Windows\SysWOW64\ntdll.dll)
> kernel32.dll	A: 0x76350000 - 0x76460000	(C:\Windows\syswow64\kernel32.dll)
> KERNELBASE.dll	A: 0x76200000 - 0x76246000	(C:\Windows\syswow64\KERNELBASE.dll)
> SHELL32.dll	A: 0x75120000 - 0x75D6A000	(C:\Windows\syswow64\SHELL32.dll)
> msvcrt.dll	A: 0x762A0000 - 0x7634C000	(C:\Windows\syswow64\msvcrt.dll)
> SHLWAPI.dll	A: 0x76800000 - 0x76857000	(C:\Windows\syswow64\SHLWAPI.dll)
> GDI32.dll	A: 0x74D70000 - 0x74E00000	(C:\Windows\syswow64\GDI32.dll)
> USER32.dll	A: 0x74F90000 - 0x75090000	(C:\Windows\syswow64\USER32.dll)
> ADVAPI32.dll	A: 0x76460000 - 0x76500000	(C:\Windows\syswow64\ADVAPI32.dll)
> sechost.dll	A: 0x765F0000 - 0x76609000	(C:\Windows\SysWOW64\sechost.dll)
> RPCRT4.dll	A: 0x76500000 - 0x765F0000	(C:\Windows\syswow64\RPCRT4.dll)
> SspiCli.dll	A: 0x74D10000 - 0x74D70000	(C:\Windows\syswow64\SspiCli.dll)
> CRYPTBASE.dll	A: 0x74D00000 - 0x74D0C000	(C:\Windows\syswow64\CRYPTBASE.dll)
> LPK.dll	A: 0x74F80000 - 0x74F8A000	(C:\Windows\syswow64\LPK.dll)
> USP10.dll	A: 0x75D70000 - 0x75E0D000	(C:\Windows\syswow64\USP10.dll)
> WSOCK32.dll	A: 0x72810000 - 0x72817000	(C:\Windows\system32\WSOCK32.dll)
> WS2_32.dll	A: 0x76260000 - 0x76295000	(C:\Windows\syswow64\WS2_32.dll)
> NSI.dll	A: 0x77180000 - 0x77186000	(C:\Windows\syswow64\NSI.dll)
> WINMM.dll	A: 0x729D0000 - 0x72A02000	(C:\Windows\system32\WINMM.dll)
> IMM32.DLL	A: 0x75090000 - 0x750F0000	(C:\Windows\system32\IMM32.DLL)
> MSCTF.dll	A: 0x76730000 - 0x767FC000	(C:\Windows\syswow64\MSCTF.dll)
> mysql.DLL	A: 0x6D570000 - 0x6D8C2000	(D:\Desktop\PAWN\SA-MP\BLCnR\plugins\mysql.DLL)
> libmariadb.dll	A: 0x6D490000 - 0x6D56E000	(D:\Desktop\PAWN\SA-MP\BLCnR\libmariadb.dll)
> api-ms-win-core-synch-l1-2-0.DLL	A: 0x72A40000 - 0x72A43000	(C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL)
> NLAapi.dll	A: 0x73CD0000 - 0x73CE0000	(C:\Windows\system32\NLAapi.dll)
> napinsp.dll	A: 0x725C0000 - 0x725D0000	(C:\Windows\system32\napinsp.dll)
> pnrpnsp.dll	A: 0x6D470000 - 0x6D482000	(C:\Windows\system32\pnrpnsp.dll)
> mswsock.dll	A: 0x72B50000 - 0x72B8C000	(C:\Windows\System32\mswsock.dll)
> DNSAPI.dll	A: 0x72AE0000 - 0x72B24000	(C:\Windows\system32\DNSAPI.dll)
> winrnr.dll	A: 0x6D460000 - 0x6D468000	(C:\Windows\System32\winrnr.dll)
> wshbth.dll	A: 0x6D450000 - 0x6D45D000	(C:\Windows\system32\wshbth.dll)
> rasadhlp.dll	A: 0x72AA0000 - 0x72AA6000	(C:\Windows\system32\rasadhlp.dll)
> MSVCP100.dll	A: 0x72C50000 - 0x72CB9000	(C:\Windows\system32\MSVCP100.dll)
> MSVCR100.dll	A: 0x72B90000 - 0x72C4F000	(C:\Windows\system32\MSVCR100.dll)
> sscanf.DLL	A: 0x10000000 - 0x1000F000	(D:\Desktop\PAWN\SA-MP\BLCnR\plugins\sscanf.DLL)
> VCRUNTIME140.dll	A: 0x6D3E0000 - 0x6D3F5000	(C:\Windows\system32\VCRUNTIME140.dll)
> api-ms-win-crt-runtime-l1-1-0.dll	A: 0x6D3D0000 - 0x6D3D4000	(C:\Windows\system32\api-ms-win-crt-runtime-l1-1-0.dll)
> ucrtbase.DLL	A: 0x6D2F0000 - 0x6D3CC000	(C:\Windows\system32\ucrtbase.DLL)
> api-ms-win-core-timezone-l1-1-0.dll	A: 0x6D2E0000 - 0x6D2E3000	(C:\Windows\system32\api-ms-win-core-timezone-l1-1-0.dll)
> api-ms-win-core-file-l2-1-0.dll	A: 0x6D2D0000 - 0x6D2D3000	(C:\Windows\system32\api-ms-win-core-file-l2-1-0.dll)
> api-ms-win-core-localization-l1-2-0.dll	A: 0x6D2C0000 - 0x6D2C3000	(C:\Windows\system32\api-ms-win-core-localization-l1-2-0.dll)
> api-ms-win-core-processthreads-l1-1-1.dll	A: 0x6D2B0000 - 0x6D2B3000	(C:\Windows\system32\api-ms-win-core-processthreads-l1-1-1.dll)
> api-ms-win-core-file-l1-2-0.dll	A: 0x6D2A0000 - 0x6D2A3000	(C:\Windows\system32\api-ms-win-core-file-l1-2-0.dll)
> api-ms-win-crt-string-l1-1-0.dll	A: 0x6D290000 - 0x6D294000	(C:\Windows\system32\api-ms-win-crt-string-l1-1-0.dll)
> api-ms-win-crt-heap-l1-1-0.dll	A: 0x6D280000 - 0x6D283000	(C:\Windows\system32\api-ms-win-crt-heap-l1-1-0.dll)
> api-ms-win-crt-stdio-l1-1-0.dll	A: 0x6D270000 - 0x6D274000	(C:\Windows\system32\api-ms-win-crt-stdio-l1-1-0.dll)
> api-ms-win-crt-convert-l1-1-0.dll	A: 0x6D260000 - 0x6D264000	(C:\Windows\system32\api-ms-win-crt-convert-l1-1-0.dll)
> streamer.DLL	A: 0x6D210000 - 0x6D25C000	(D:\Desktop\PAWN\SA-MP\BLCnR\plugins\streamer.DLL)
> MSVCP140.dll	A: 0x6D1A0000 - 0x6D20D000	(C:\Windows\system32\MSVCP140.dll)
> api-ms-win-crt-locale-l1-1-0.dll	A: 0x6D190000 - 0x6D193000	(C:\Windows\system32\api-ms-win-crt-locale-l1-1-0.dll)
> api-ms-win-crt-math-l1-1-0.dll	A: 0x6D180000 - 0x6D185000	(C:\Windows\system32\api-ms-win-crt-math-l1-1-0.dll)
> api-ms-win-crt-multibyte-l1-1-0.dll	A: 0x6D170000 - 0x6D175000	(C:\Windows\system32\api-ms-win-crt-multibyte-l1-1-0.dll)
> api-ms-win-crt-time-l1-1-0.dll	A: 0x6D160000 - 0x6D163000	(C:\Windows\system32\api-ms-win-crt-time-l1-1-0.dll)
> api-ms-win-crt-filesystem-l1-1-0.dll	A: 0x6D150000 - 0x6D153000	(C:\Windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll)
> api-ms-win-crt-environment-l1-1-0.dll	A: 0x6D140000 - 0x6D143000	(C:\Windows\system32\api-ms-win-crt-environment-l1-1-0.dll)
> api-ms-win-crt-utility-l1-1-0.dll	A: 0x6D130000 - 0x6D133000	(C:\Windows\system32\api-ms-win-crt-utility-l1-1-0.dll)
> whirlpool.DLL	A: 0x00530000 - 0x0053C000	(D:\Desktop\PAWN\SA-MP\BLCnR\plugins\whirlpool.DLL)
> MSVCR80.dll	A: 0x73570000 - 0x7360B000	(C:\Windows\WinSxS\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.4940_none_d08cc06a442b34fc\MSVCR80.dll)
> nativechecker.DLL	A: 0x6D120000 - 0x6D125000	(D:\Desktop\PAWN\SA-MP\BLCnR\plugins\nativechecker.DLL)
> wshtcpip.dll	A: 0x72B40000 - 0x72B45000	(C:\Windows\System32\wshtcpip.dll)
> IPHLPAPI.DLL	A: 0x72AC0000 - 0x72ADC000	(C:\Windows\system32\IPHLPAPI.DLL)
> WINNSI.DLL	A: 0x72AB0000 - 0x72AB7000	(C:\Windows\system32\WINNSI.DLL)
> wship6.dll	A: 0x72B30000 - 0x72B36000	(C:\Windows\System32\wship6.dll)
> PROPSYS.dll	A: 0x70FF0000 - 0x710E5000	(C:\Windows\system32\PROPSYS.dll)
> OLEAUT32.dll	A: 0x76C90000 - 0x76D1F000	(C:\Windows\syswow64\OLEAUT32.dll)
> comctl32.dll	A: 0x71170000 - 0x7130E000	(C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2\comctl32.dll)
> apphelp.dll	A: 0x70F40000 - 0x70F8C000	(C:\Windows\system32\apphelp.dll)
> CLBCatQ.DLL	A: 0x76D20000 - 0x76DA3000	(C:\Windows\syswow64\CLBCatQ.DLL)
> iertutil.dll	A: 0x75E20000 - 0x7601B000	(C:\Windows\syswow64\iertutil.dll)
> urlmon.dll	A: 0x74E40000 - 0x74F76000	(C:\Windows\syswow64\urlmon.dll)
> WININET.dll	A: 0x76AB0000 - 0x76BA5000	(C:\Windows\syswow64\WININET.dll)
> CRYPT32.dll	A: 0x76610000 - 0x7672D000	(C:\Windows\syswow64\CRYPT32.dll)
> MSASN1.dll	A: 0x74E00000 - 0x74E0C000	(C:\Windows\syswow64\MSASN1.dll)
> SETUPAPI.dll	A: 0x76880000 - 0x76A1D000	(C:\Windows\syswow64\SETUPAPI.dll)
> CFGMGR32.dll	A: 0x76BB0000 - 0x76BD7000	(C:\Windows\syswow64\CFGMGR32.dll)
> DEVOBJ.dll	A: 0x76860000 - 0x76872000	(C:\Windows\syswow64\DEVOBJ.dll)
> ntmarta.dll	A: 0x70EE0000 - 0x70F01000	(C:\Windows\system32\ntmarta.dll)
> WLDAP32.dll	A: 0x76C40000 - 0x76C85000	(C:\Windows\syswow64\WLDAP32.dll)
> profapi.dll	A: 0x720C0000 - 0x720CB000	(C:\Windows\system32\profapi.dll)
> VERSION.dll	A: 0x725B0000 - 0x725B9000	(C:\Windows\system32\VERSION.dll)

**mysql_log.txt**

> [23:30:22 02/04/17] [DEBUG] mysql_connect - host: "eu9.hostskool.com", user: "AqeelM", database: "AqeelM", password: "****", port: 3306, autoreconnect: true, pool_size: 2
> [23:30:22 02/04/17] [DEBUG] CMySQLHandle::Create - creating new connection..
> [23:30:22 02/04/17] [DEBUG] CMySQLHandle::CMySQLHandle - constructor called
> [23:30:22 02/04/17] [DEBUG] CMySQLHandle::Create - connection created (id: 1)
> [23:30:22 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
> [23:30:23 02/04/17] [DEBUG] mysql_errno - connection: 1
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - connection was successful
> [23:30:23 02/04/17] [DEBUG] CMySQLConnection::Connect - auto-reconnect has been enabled
> [23:30:25 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
> [23:30:25 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
> [23:30:25 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
> [23:30:25 02/04/17] [DEBUG] CMySQLConnection::Disconnect - connection was closed
> [23:30:25 02/04/17] [DEBUG] CMySQLHandle::~CMySQLHandle - deconstructor called

By **REMOVING** crashdetect and loading mysql as usual place(#3) problem was solved
Im using crashdetect 4.18.1... also tested with old versions of crashdetect

**Comment by Yousha** [comment]
Fixed by using `mysql_close()` in gamemode exit callback.
