### ISSUE TITLE
Suggestion: orm_addvalue_*

### ISSUE THREAD

**Issue by Dayvison** [pBlueG/SA-MP-MySQL#145]
```pawn
native orm_addvalue_int(ORM:id, value, const columnname[]);
native orm_addvalue_float(ORM:id, Float:value, const columnname[]);
native orm_addvalue_string(ORM:id, value[], var_maxlen, const columnname[]);
```
Different from `addvar` this needs be used every time.

**Comment by maddinat0r** [comment]
This is not the purpose of the ORM system. It's all about assigning variables to columns once, and then only calling functions to load and store those variables. Not assigning variables but instead calling a native which specifies the value for the bound column every time before issuing a load/store command completely misses the point of the whole ORM feature.

**Comment by Dayvison** [comment]
Ok i get it
