### ISSUE TITLE
Suggestion: cache_delete_row

### ISSUE THREAD

**Issue by Dayvison** [pBlueG/SA-MP-MySQL#146]
Example:
- cache_num_rows > 4
- cache_delete_row > 3(now the rowid 4 becomes 3)
- cache_num_rows > 3

**Comment by maddinat0r** [comment]
What would be a valid use-case for this?
You usually specify the data you want through your query. Filtering the (cached) data client-side is pretty stupid, considering you're using a database server which has a whole language built around the concept of fetching and filtering data.

**Comment by Dayvison** [comment]
**query** `SELECT `COLUMN_NAME`, `COLUMN_TYPE` FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'base' AND TABLE_NAME ='user';`
After this query, many times will be called this function, base on returned cache
 if have cache_delete_row i don't need check all columns name every time, but still working here. if you not see this a good not add p.p is just a suggestion :)
```pawn
/**
 * Checa a coluna referente modo em que completa a tabela
 *
 * @param      column    Nome da coluna
 * @param      datatype  Tipo dedados que salva
 *
 * @date       14:38 25/03/2017
 * @author     Dayvison
 *
 * @return     --
 */
stock void:checkColumn(const string:column[], const string:datatype[]) <uvar_type: complete>
{
	P:function_call("checkColumn(column=\"%s\", datatype=\"%s\") <uvar_type: complete>", column, datatype);
	new
		rows,
		rowid = -1,
		hash = YHash(column),
		name[32]
	;
	cache_get_row_count(rows);
	loop:i(5, rows)
	{
		cache_get_value_index(i, 0, name);
		if(hash == YHash(name))
		{
			if(!strcmp(column, name))
			{
				rowid = i;
				break;
			}
		}
	}
	// Coluna não existe
	if(rowid == -1)
	{
		++columnsCreated;
		P:function_deep("Coluna [`%s` %s] não existe.", column, datatype);
		mysql_format(cHandle, gs_QueryBuffer, sizeof(gs_QueryBuffer), "ALTER TABLE `"#USERS_TABLE"` ADD `%s` %s;", column, datatype);
		mysql_pquery(cHandle, gs_QueryBuffer);
	}
	else
	{
		cache_get_value_index(rowid, 1, name);
		//cache_delete_row(rowid);
		if(strcmp(datatype, name))
		{
			++columnsModified;
			P:function_deep("Coluna [`%s` %s] existe porém com um tipo de dados diferente: `%s`.", column, datatype, name);
			mysql_format(cHandle, gs_QueryBuffer, sizeof(gs_QueryBuffer), "ALTER TABLE `"#USERS_TABLE"` MODIFY COLUMN `%s` %s;", column, datatype);
			mysql_pquery(cHandle, gs_QueryBuffer);
		}
	}
	P:function_end("checkColumn(column=\"%s\", datatype=\"%s\") <uvar_type: complete>", column, datatype);
}
```

**Comment by maddinat0r** [comment]
Sorry for the late response.
I really don't like the idea making the cache alterable. The cache is a copy of the result data from a MySQL query with a longer life span than the actual result data. Both are not meant to be modified.
Still, thanks for the suggestion!
