### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by karimcambridge** [pBlueG/SA-MP-MySQL#152]
https://pastebin.com/EKnGU9wH

**Comment by karimcambridge** [comment]
https://pastebin.com/6C4DH1MV

Will take awhile for me to get a debug plugin. If someone can compile one on ubuntu 16.04 for me..

**Comment by karimcambridge** [comment]
Could there be a memory issue?

https://pastebin.com/k7ctVM90

**Comment by maddinat0r** [comment]
Hm, seems like a memory issue, since both backtraces only allocate/free up memory during the crash.
It's probably something on your side. Maybe your server is running out of memory?
