### ISSUE TITLE
mysql_connect_file problem

### ISSUE THREAD

**Issue by WizardFtw** [pBlueG/SA-MP-MySQL#153]
Im trying to connect mysql server with mysql_connect_file function, but I having problems. When is starting, I receive this message on mysql log.

[plugins/mysql] mysql_connect_file: handle error: syntax error in connection file (line: "﻿hostname = 127.0.0.1")

but mysql.ini look be fine...

> hostname = 127.0.0.1
username = myusername
password = mypass
database = mydb
auto_reconnect = true
#multi_statements = false
#pool_size = 2
#server_port = 3306

This only happens when I use mysql_connect_file function, with mysql_connect not.

Is there a problem with the function or am I not using it properly?

Im sorry if my English drafting is shit, it's not my native language.

**Comment by maddinat0r** [comment]
Can you upload the mysql.ini you used here? Just drag-and-drop the file into the text box.

**Comment by WizardFtw** [comment]
of course! but said "We don't support that file type"

here link: [https://mega.nz/#!MI0jDTAA!IGHT7tx7pQaoQzR_6VYJPXO6oJ8ews5hX1VHX5ONU10](url)

**Comment by maddinat0r** [comment]
Your file encoding is incorrect. Currently, it's UTF8-BOM. It should only be UTF8 though. BOM encodings are not supported.

**Comment by WizardFtw** [comment]
Oh, thanks. I didn't know that only support UTF8 encoding.

Solved.
