### ISSUE TITLE
Problem with 'mysql_set_charset'

### ISSUE THREAD

**Issue by canciftci** [pBlueG/SA-MP-MySQL#156]
Hey there, I'm trying to use foreign characters in my database but seems like it's not supported or I am doing something WRONG.

MySQL connection:

sqlbaglanti = mysql_connect_file("slymind.ini");
mysql_set_charset("latin5_turkish_ci",sqlbaglanti);

MySQL LOG:

[DEBUG] CHandle::GetErrorId - return value: true, error id: '2019', error msg: 'Can't initialize character set latin5_turkish_ci (path: compiled_in)'
[DEBUG] mysql_errno: return value: '2019'

**Comment by canciftci** [comment]
Well, I changed all of my MySQL tables' to latin5_turkish_ci but I still have the same issue, when I change the value manually, it shows foreign characters but when I load it in-game it doesn't show up and when I change the value using MySQL query UPDATE, it still has the same problem.

**Comment by maddinat0r** [comment]
Make sure your MySQL server is properly configured. Check if you have a setting in your server config file named `character-sets-dir` and if it's correctly set to the charset directory.

**Comment by canciftci** [comment]
Well, seems like this issue came up with the latest version of this plugin. It used to work fine in earlier versions.

It's really weird to be honest, I've been using your MySQL plugin for years but this is the first time it's happening (it actually has happened before but I fixed it by changing my tables to latin5_turkish_ci)

**Comment by canciftci** [comment]
Alright, I fixed it by uninstalling AppServ and installing WAMP, I've no clue of why that happened but it is just fixed now.

Thanks man, you may close this, if you want to.

**Comment by canciftci** [comment]
I couldn't fix it, I guess?
Now, I can save it properly but when I load it from the database it still won't show Turkish characters, UPDATE queries works fine but loading is not the same.

**Comment by canciftci** [comment]
I don't get any errors from now on, mysql set charset works pretty fine now.
Thanks anyways!

**Comment by maddinat0r** [comment]
Sorry for not responding.
Glad everything worked out!
