### ISSUE TITLE
Unloading plugin hang on rcon exit

### ISSUE THREAD

**Issue by kubkox3** [pBlueG/SA-MP-MySQL#158]
Well, I have global variable to which I store cached data after selection.
I've noticed that when I have inserted into table like 3000 rows, afterwards selecting them together with row - variable assign loop works also butter smooth. But problem (?) occurs on rcon exit (gmx seems to  #be working fine) when it actually takes like 50 second to shutdown I can see msg "plugin.mysql: Unloading plugin...". I don't save any cache anywhere as I've loaded data in callback.

What is causing this? Thank you.

Edit: It seems that Linux hosted server is working fine, just Windows is doing it

**Comment by maddinat0r** [comment]
Can you share your mysql.log file?

**Comment by kubkox3** [comment]
Oh, I think I got it. The issue was, that as I inserted 3 thousand of rows into table, some fields of the table were NULL, it was also throwing an error into log.

Now, when I inserted it correctly the exit works just fine as it should.

**Comment by maddinat0r** [comment]
Ah, that means the server hanged because it was still writing the error log lines. It probably worked so fast on Linux because you either use a SSD there or your table was valid.
