### ISSUE TITLE
Not actually a plugin bug but inquiry

### ISSUE THREAD

**Issue by kubkox3** [pBlueG/SA-MP-MySQL#160]
Hello, today I've investigated that my MysQL query has thrown an error like this for first time. It probably has something with MySQL server that I used.
[16:28:19] [ERROR] error #2013 while executing query "SELECT * FROM `player_main` WHERE `name` = REPLACE('Kubko Dev', ' ', '_')": Lost connection to MySQL server during query

Well, but when my query failed the callback specified in tquery function didn't get called. So I was thinking about solving it and I found OnQueryError callback. It's fine actually, there's parameter for specified callback but not format meaning I can't determinate which playerid has fired the query. I would actually know alternative how to possibly determinate which playerid has the error through loop by picking it's WHERE name (Kubko_Dev at this case) and variable player loop check inside that OnQueryError.

But isn't here more efficient way I could determinate that playerid parsed in tquery?
That's why I would like to do it, becouse MDC is scripted that way it suspends cursor till query finishes. But I can't catch this error to display on player's MDC unless I get that playerid inside OnQueryError.

Thank you!

![up](https://user-images.githubusercontent.com/29288175/27712549-cc695bc4-5d27-11e7-95d5-dffce9e510bc.png)

**Comment by kubkox3** [comment]
I've got an idea, will be comment specified in query parsed also parsed to OnQueryError?

If I would do SELECT * FROM player_main WHERE name = REPLACE('Kubko Dev', ' ', '_')  ; # playerid=7

**Comment by maddinat0r** [comment]
Sorry for the late response.
Yes, you can add SQL comments and parse them later in OnQueryError.
