### ISSUE TITLE
[MySQL R41-3] system error: 10060

### ISSUE THREAD

**Issue by CheRrySMinT** [pBlueG/SA-MP-MySQL#163]
I don't know anything, i'll just leave it there. 
(With version R41-2 all works perfectly, idk why. These are errors when starting server with R41-3)

> [21:04:18] [ERROR] CConnection::CConnection - establishing connection to MySQL database failed: #2013 'Lost connection to MySQL server at 'reading authorization packet', system error: 10060'
[21:04:19] [ERROR] CConnection::CConnection - establishing connection to MySQL database failed: #2013 'Lost connection to MySQL server at 'reading authorization packet', system error: 10060'
[21:04:20] [ERROR] CConnection::CConnection - establishing connection to MySQL database failed: #2013 'Lost connection to MySQL server at 'reading authorization packet', system error: 10060'
[21:04:21] [ERROR] CConnection::CConnection - establishing connection to MySQL database failed: #2013 'Lost connection to MySQL server at 'reading authorization packet', system error: 10060'

**Comment by maddinat0r** [comment]
Are you on Windows or on Linux (distribution name + version please)? Do you use the static version?

**Comment by DenomZ** [comment]
I'm experiencing the same problem on windows.. I reverted back to R41-2

**Comment by JustDeimos** [comment]
I apologize in advance for my English.
Met with the same problem as the author.
System: Windows 8.1
Plug-in version: R41-3
On the R41-2 version, there is no error.

**Comment by maddinat0r** [comment]
Which version is your MySQL server?

**Comment by JustDeimos** [comment]
Ver 14.14 Distrib 5.5.53, for Win32 (AMD64)

This?
Now I'll try to put a newer version and write about what happened

**Comment by JustDeimos** [comment]
The problem is observed on all versions, starting with 5.5 and ending with 5.7. Other versions so far there is no way to check if there is any need at all.

**Comment by maddinat0r** [comment]
I can't reproduce this issue on a clean SA-MP server with R41-3 and a fresh MySQL 5.5.57 server.
Try deleting all plugin-related files (`mysql.dll`, `libmariadb.dll`, `libmysql.dll` (if there is one), `a_mysql.inc`), re-download R41-3, place it into your SA-MP server folder and recompile your script.

**Comment by JustDeimos** [comment]
https://www.youtube.com/watch?v=Y-vv9FMh9RE&feature=youtu.be

I am ready to help in every way to solve this problem. Just tell me what to do.

**Comment by maddinat0r** [comment]
Can you try to replace your current `libmariadb.dll` with that one from the R41-2 package?

**Comment by JustDeimos** [comment]
It worked. The error has disappeared.

**Comment by maddinat0r** [comment]
Can you [try out this build](https://github.com/pBlueG/SA-MP-MySQL/files/1290751/mysql-R41-3-win32.zip) please?

**Comment by JustDeimos** [comment]
Working

**Comment by maddinat0r** [comment]
Okay, I'll bump the version and release this as R41-4. Thanks for your help!
