### ISSUE TITLE
mysql transactions not working

### ISSUE THREAD

**Issue by alterego29** [pBlueG/SA-MP-MySQL#169]
`BEGIN; INSERT INTO `accounts` (username, salt, password) VALUES ('%e', '%e', '%e'); SET @last_id = LAST_INSERT_ID(); INSERT INTO `status` (userid) VALUES (@last_id); INSERT INTO `levels` (userid) VALUES (@last_id); INSERT INTO `deathmatch` (userid) VALUES (@last_id); COMMIT;`
`
I tried doing this line of transaction code and queried it in the game it does not insert or do anything.

But on the phpmyadmin, specifically I'm using HeidiSQL as Interface and it works fine does not show any error.

and yes I've already tried using START TRANSACTION; replacing BEGIN; but no it's still doesn't work
I'm using the latest include already and plugin...

> EDIT:
> `[00:07:30] [plugins/mysql] cache_get_value_name_int: field 'tddeaths' not found (C:\Users\JesterlJoker\Desktop\NeoGRP\gamemodes\neogrp\includes\customcallbacks.inc:119 -> C:\Users\JesterlJoker\Desktop\NeoGRP\gamemodes\neogrp\includes\functions.inc:55 -> C:\Users\JesterlJoker\Desktop\NeoGRP\gamemodes\neogrp\includes\customcallbacks.inc:25)
> [00:07:30] [plugins/mysql] cache_get_value_name_int: field 'dkills' not found (C:\Users\JesterlJoker\Desktop\NeoGRP\gamemodes\neogrp\includes\customcallbacks.inc:120 -> C:\Users\JesterlJoker\Desktop\NeoGRP\gamemodes\neogrp\includes\functions.inc:55 -> C:\Users\JesterlJoker\Desktop\NeoGRP\gamemodes\neogrp\includes\customcallbacks.inc:25)`
> This is the error log well there's no problem really it just logs this even if it already loaded everything proplerly
> This not really a heavy issue but everytime the server does this it will propagate the logs and will increase storage
> 
> EDIT2:
> I tested the same functions and callback on a blank test pawn and the error did not show up... I don't know what went wrong but I just copy pasted the code from my main gamemode so something must be up...

EDIT 3:
I fixed the lower problems I quoted them, the wrong thing I did was because I hadn't used the JOIN function correctly and now it's corrected and also have some typo's
 the only issue I have is the transaction thing, it still does not work, am I doing something wrong?

**Comment by maddinat0r** [comment]
You can't send multi-statement queries unless you explicitly enable this (option `MULTI_STATEMENTS`). You'll have to do transactions like this:
```pawn
mysql_tquery(sql, "START TRANSACTION");
mysql_tquery(sql, "INSERT INTO accounts(username, salt, password) VALUES ('%e', '%e', '%e')");
mysql_tquery(sql, "SET @last_id = LAST_INSERT_ID()");
mysql_tquery(sql, "INSERT INTOstatus(userid) VALUES (@last_id)");
mysql_tquery(sql, "INSERT INTOlevels(userid) VALUES (@last_id)");
mysql_tquery(sql, "INSERT INTOdeathmatch(userid) VALUES (@last_id)");
mysql_tquery(sql, "COMMIT");
```

**Comment by maddinat0r** [comment]
You should also check your logs for any errors.

**Comment by alterego29** [comment]
Yeah thanks, I just forgot to read through the mysql include... thanks by the way

**Comment by maddinat0r** [comment]
`BEGIN` is an alias for `START TRANSACTION`, however the latter is generally preferred, as it is standard SQL syntax.
