### ISSUE TITLE
Returning result in a function

### ISSUE THREAD

**Issue by MrDomas** [pBlueG/SA-MP-MySQL#172]
Hello. I'm trying to get a username by userid from database.

Using a function:
GetUserNameFromDatabase(userId). It has to return a username.

I've tried many ways to get it, but it doesn't work. Any help?

**Comment by mikroware** [comment]
What is the content of `GetUserNameFromDatabase`? The queries you execute with this plugin will be executed in another thread and will not directly result in an answer. Each query call will have a callback method, which is called when the results are ready. Hence it is not possible for a function like `GetUserNameFromDatabase` to return the username.

There are two basic solutions:
- Continue with what you want to do in the query callback function.
- Load the username in a variable when the player info is loaded, that way you can directly access it.

**Comment by MrDomas** [comment]
I need information from offline user.

```
stock GetUserNameFromDatabase(userid)
{
	new
		Cache:result,
		query[256],
		username[32];

	if(userid == INVALID_PLAYER_ID) {
		format(username, sizeof(username), "Serveris");
		return username;
	}

	mysql_format(database, query, sizeof(query), "SELECT `username` FROM `users` WHERE `id` = %d", userid);
	result = mysql_query(database, query);

	cache_get_value_name(0, "username", username);
	cache_delete(result);

	return username;
}
```

This is my current function and it works. But it is good for use?

**Comment by mikroware** [comment]
Ah you are using `mysql_query`. (as mentioned here, it is not recommended http://wiki.sa-mp.com/wiki/MySQL#mysql_query)

Are you sure the query is called and that there is even a result? Try using http://wiki.sa-mp.com/wiki/MySQL#cache_get_row_count.

**Comment by maddinat0r** [comment]
Your function is fine. Just don't forget that this function will reset any active cache.
