### ISSUE TITLE
extended mysql_format function?

### ISSUE THREAD

**Issue by pds2k12** [pBlueG/SA-MP-MySQL#173]
Well I planning to move from SQLite to MySQL as the sa-mp sqlite version is really outdated and does not support association tables, such as **db_query** in **a_sampdb** does not support **ON DELETE CASCADE** but doing so would require a lot of time therefore I thought of something really useful that is somewhat similar to **prepared statements**. This is not only for my own advantage but could be useful for other users in future. 

example of db_query in SQLITE using **SQLite Improved**

```		
db_query(dbHandle, "UPDATE accounts SET \
    name = ?, score = ?, health = ? WHERE accountID = ?", STRING:"new_name", INT:5, FLOAT:"92.18", INT:0); 
// UPDATE accounts SET name = 'new_name', score = 5, health = 92.18 WHERE accountID = 0;
```

psuedo code of the new mysql_format function using **MySQL**
```
new 
    tmp_sQuery[128];

mysql_format(dbHandle, tmp_sQuery, sizeof(tmp_sQuery), "UPDATE accounts SET \
    name = ?, score = ?, health = ?, WHERE accountID = ?",  STRING:"new_name", INT:5, FLOAT:"92.18", INT:0);
mysql_pquery(dbHandle, tmp_sQuery, "OnDataLoad", "i", playerid);

//UPDATE accounts SET name = 'new_name', score = 5, health = 92.18 WHERE accountID = 0;
```

or somewhere along those lines, this is just an idea but it would be nice to implent something like this, the reason WHY? it improves readability by ALOT! 

An example of this kind of scheme taken from a code that I am currently doing.

https://pastebin.com/ns0cbZ6c

**Comment by maddinat0r** [comment]
I really don't want to add stuff like this directly into the plugin include. Some people might like this, but some might find this confusing to use or dislike the syntax. Convenience functions like this should be made available through 3rd-party includes. I just want to provide the "basic tools".
