### ISSUE TITLE
[ERROR] CCallback::Execute - invalid AMX instance

### ISSUE THREAD

**Issue by Abyss-z94** [pBlueG/SA-MP-MySQL#177]
Hi, i have some trouble when using gmx command with mysql plugin (R41-4), it alway show up that error message and sometime it made my server crash. I don't know what went wrong here 

> https://youtu.be/yFPRZSX1tp8

in my OnGamemodeExit

> public OnGameModeExit()
> {
> 	Loop:(i, 0, MAX_PLAYERS)
> 	{
> 		if(FCNPC_IsValid(i))
> 		{
> 			FCNPC_Destroy(i);
> 		}
> 	}
> 
> 	mysql_close(MainPipeline);
> 	Profiler_Stop();
> 	return 1;
> }

**Comment by maddinat0r** [comment]
Enable full logging, reproduce your issue and upload your mysql.log here.

**Comment by Abyss-z94** [comment]
How to enable full logging? i have no idea about that

**Comment by Abyss-z94** [comment]
I got that, here you go
[mysql.log](https://github.com/pBlueG/SA-MP-MySQL/files/1581379/mysql.log)

**Comment by maddinat0r** [comment]
There is no error message in your log file. Make sure you properly reproduce your problem/crash.

**Comment by Abyss-z94** [comment]
Here i guess, the file after using gmx command
[mysql.log](https://github.com/pBlueG/SA-MP-MySQL/files/1581946/mysql.log)

**Comment by maddinat0r** [comment]
It seems like you're doing UPDATE queries with a result callback at `OnGameModeExit`. However, your gamemode gets unloaded after `OnGameModeExit` finishes executing, but you specified that you want your result callback `OnQueryFinish` to be called - which doesn't work, as at that point the AMX was unloaded and is thus invalid.
So, you can either ignore that error (as in your case it doesn't cause harm), or you can fix this by not setting a result callback in your `mysql_tquery` calls in `OnGameModeExit`.

**Comment by Abyss-z94** [comment]
I got it, thank you for your help. I'll re-check all of callback in OnGameModeExit now :D, seem like not a big deal.

**Comment by maddinat0r** [comment]
Feel free to close this issue when you manage to resolve your errors.
