### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by Romz24** [pBlueG/SA-MP-MySQL#179]
I suggest adding a few function for working with arrays:

> native orm_addvar_array(ORM:id, var[], const format[], const columnname[]);
> native cache_get_value_name_array(row_idx, const columnname[], destination[], const format[]);

Example of work:
> new mycolor[3];
> mycolor[0] = 3;
> mycolor[1] = 5;
> mycolor[2] = 0;
> orm_addvar_array(ormid, mycolor, "|", "color"); // color='3|5|0'

> new mycolor[2];
> cache_get_value_name_array(row, "color", mycolor, "|");

**Comment by maddinat0r** [comment]
Storing whole arrays into a single column violates the [first normal form of database normalization](https://en.wikipedia.org/wiki/First_normal_form). Check out [this](http://forum.sa-mp.com/showthread.php?t=420363) and [this](http://forum.sa-mp.com/showthread.php?t=505081) tutorial to learn how to properly design your database.

**Comment by m1n1vv** [comment]
I represent the preservation of weapons 😆. +90 fields 😆😆😆
