### ISSUE TITLE
Include line number of code in function log messages

### ISSUE THREAD

**Issue by maddinat0r** [pBlueG/SA-MP-MySQL#18]
Use the `__line` define introduced by Zeex in his PAWN compiler patches to provide more information about where in a user's code an error happened.

**Comment by maddinat0r** [comment]
Scrap that idea with the `__line` define, I'll use the AMX debug symbol table for this (this requires to compile a script with debug flags like `-d3` though).

**Comment by WopsS** [comment]
:+1:

**Comment by maddinat0r** [comment]
Fixed in [maddinat0r/samp-log-core](https://github.com/maddinat0r/samp-log-core).
