### ISSUE TITLE
Upgraded to R41.4 (from 39.6) getting errors and warnings

### ISSUE THREAD

**Issue by kubkox3** [pBlueG/SA-MP-MySQL#182]
Well, I decided to keep my large gamemode script up to date, so I managed to download and get prepared my script for new include functions, which have changed, all went fine though. The only problem is that I got some weird errors & warning and I have no idea, what can be wrong.

0.3.8\pawno\include\YSI\y_inline.inc(1110) : warning 209: function "Callback_Call" should return a value
0.3.8\pawno\include\a_mysql.inc(33) : error 001: expected token: "-identifier-", but found "-integer value-"
0.3.8\pawno\include\a_mysql.inc(38) : error 010: invalid function or declaration
0.3.8\pawno\include\a_mysql.inc(39) : error 010: invalid function or declaration
0.3.8\pawno\include\a_mysql.inc(144) : error 017: undefined symbol "ERROR"

As I said, I've rechecked all new functions, if I have them written correctly in my gamemode, they should be. Thank you very much. :)

**Comment by kubkox3** [comment]
When I delete E_LOG enum completely and edit mysql_log native to this native mysql_log(loglevel = 1); it compiles just with one warning:

YSI\y_inline.inc(1110) : warning 209: function "Callback_Call" should return a value

**Comment by kubkox3** [comment]
Well I did an update to YSI v4 and warning is gone.

**Comment by maddinat0r** [comment]
So, did you manage to resolve everything? Can I close this now?

**Comment by kubkox3** [comment]
Yes I did, thank you for the answer anyway.
