### ISSUE TITLE
Not load OwnerName on server

### ISSUE THREAD

**Issue by Mariusik1800** [pBlueG/SA-MP-MySQL#186]
Does anyone know what I did wrong, do not load the name of the car owner on the server?
cache_get_value_name(i, "CarOwner", CarData[id][cOwner]);

**Comment by maddinat0r** [comment]
Plugin errors are logged to the plugin-specific `mysql.log` *and* error-specific `errors.log` log file. Check one of those files. If there's no error logged, it then very likely is a problem in your script.
