### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by maddinat0r** [pBlueG/SA-MP-MySQL#19]
Error messages have to be improved. Currently, they aren't much of a help (okay, sometimes the error is clear, but sometimes there are just obscure reports of syntax errors which don't really help anyone at all and to debug that error the user has to enable debug logging - which is unthinkable in a running server environment), so there have to be some improvements to be done.

**Comment by Kar2k** [comment]
Has this been improved yet?

"[18:16:08] [ERROR] CMySQLQuery::Execute[] - (error #1062) Duplicate entry 'david_washinton1' for key 'Username'
[18:33:57] [ERROR] CMySQLQuery::Execute[] - (error #1062) Duplicate entry 'david_washinton1' for key 'Username'
[18:37:54] [ERROR] CMySQLQuery::Execute[] - (error #1062) Duplicate entry 'david_washinton1' for key 'Username'
[18:49:47] [ERROR] CMySQLQuery::Execute[] - (error #1062) Duplicate entry 'david_washinton1' for key 'Username'"

Erm ^

**Comment by maddinat0r** [comment]
Nope, the log system is currently completely unimplemented. I'll do all log-related issues after I test the plugin in its current state (basic query execution and stuff).

**Comment by Kar2k** [comment]
forward OnQueryWarning(warningid, const warning[], const callback[], const query[], MySQL:handle);

Please see to adding that too ^

**Comment by kurta999** [comment]
That would be very useful!
