### ISSUE TITLE
No characters are displayed

### ISSUE THREAD

**Issue by encoder64x** [pBlueG/SA-MP-MySQL#190]
Do not display Russian characters after adding to the database using the function **mysql_pquery**. After a change on the **mysql_tquery**, everything worked. 
What is the reason for this?

**Comment by maddinat0r** [comment]
Are you, by any chance, manually setting the character set through a query (`mysql_tquery` to be specific)?

**Comment by Revoshell** [comment]
This actually happens with Cyrillic characters when using mysql_pquery.
