### ISSUE TITLE
Failed (/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by plugins/mysql.so))

### ISSUE THREAD

**Issue by VitaaoStaff** [pBlueG/SA-MP-MySQL#191]
I need to connect a server in MYSQL, but it is giving error when connecting the server.
I need the later versions of R40.
I tested with all above that version, and the same error occurs, if I get the version 39-6, the plugin performs normal, but the server does not turn on because it needs the updated version.

My VPS is CentOS 6

Loading plugin: mysql.so
[01:09:05]   Failed (/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by plugins/mysql.so))

**Comment by Jeroen52** [comment]
Supported*, damned autocorrect.

Op 6 mrt. 2018 09:54 schreef "Jeroen de Neef" <jeroen52@gmail.com>:

**Comment by VitaaoStaff** [comment]
O que eu preciso fazer então?
Atualizar para Centos7?

**Comment by Jeroen52** [comment]
There is no official upgrade to CentOS 7, you'll need to reinstall your CentOS 6 VPS to install CentOS 7.

If you want to use R39-6, which is possible. You'll need to change your code to make it compatible with R39-6.

**Comment by VitaaoStaff** [comment]
Eu ainda não entendi.
Você disse, "reinstalar o CentOS 6 para instalar o CentOS 7", mas por que eu tenho que reinstalar o CentOS 6?

**Comment by WopsS** [comment]
Can you speak in English please? 

Almost all the people who receive these notifications need to use Google Translate if they want to help you or know about the issue.

**Comment by VitaaoStaff** [comment]
Ok, I'm sorry.
I was just confused in the part that he spoke to reinstall CentOS 6, being that my VPS is already CentOS 6

**Comment by Jeroen52** [comment]
@VitaaoStaff You need to reinstall your CentOS 6 VPS **to** CentOS 7.

So you need to install CentOS _**7**_ instead of CentOS _**6**_.

**Comment by VitaaoStaff** [comment]
@Jeroen52 
Now I get it.
What you said above, gave to understand that I had to format my VPS, install CentOS 6 to be able to upgrade to CentOS 7.
But now I get it. I have already asked the company to format and install CentOS 7.

I will do the test, in case the error continues, I will mention you.

Thank you

**Comment by Jeroen52** [comment]
The next time please do read the F.A.Q. before posting an issue.

There should be no issues running the newest version of SA-MP-MySQL on CentOS 7, as there is a separate build in the Release page. As you can see after R39-6 (so from R40 and forwards) the distro changed from CentOS 6 to CentOS 7.

And please do check the F.A.Q.'s before opening an issue, your question is the first question.

>Q: I get a version GLIBCXX_3.4.15' not found error (or similar). How can I solve this?
>A: Update your system. If that still didn't work, you'll need to upgrade your Linux distribution to a version which provides the gcc 4.8 (or higher) compiler. For example, if you're on CentOS 6, which only has gcc 4.4, you'll need to upgrade to CentOS 7.

If you have exhausted solutions from the F.A.Q. and can still not resolve your issue, then you are encouraged to open a ticket in English.

**Comment by VitaaoStaff** [comment]
@Jeroen52 ok, sorry

**Comment by VitaaoStaff** [comment]
@Jeroen52 
I upgraded to centos 7 and the error continues, but agr the version of that GLIBC has changed

Loading plugin: mysql.so
[23:07:19]   Failed (/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by plugins/mysql.so))

**Comment by Jeroen52** [comment]
`yum whatprovides /lib/libstdc++.so.6` indicates the following:

`libstdc++-4.8.5-16.el7_4.1.i686 : GNU Standard C++ Library
Repo        : @updates
Matched from:
Filename    : /lib/libstdc++.so.6
`

Try to run `yum groupinstall 'Development Tools'` and afterwards make sure that the package you actually need is installed using `yum install libstdc++.i686`

Then try to run it again.

**Comment by VitaaoStaff** [comment]
@Jeroen52 It worked!!! 
Thank you very much!!!!
