### ISSUE TITLE
Question: Set path for logs ?

### ISSUE THREAD

**Issue by Yousha** [pBlueG/SA-MP-MySQL#199]
Can we change default **mysql_logs.txt** path? for example set it to `scriptfiles/logs`

**Comment by maddinat0r** [comment]
If you're talking about R39-6: No, this release will not get any further updates (except critical bug fixes).
If you're talking about R40 and higher: Open up an issue in the [log-core](https://github.com/maddinat0r/samp-log-core) repository.
