### ISSUE TITLE
Pre r40 (?) doesn't work with SAMPCTL

### ISSUE THREAD

**Issue by GoodBlokeAri** [pBlueG/SA-MP-MySQL#209]
Spoke to Southclaw and he mentioned it having something to do with the way versioning is on this git?

![error1](https://i.imgur.com/o4KiScH.png "Error 1")
![error2](https://i.imgur.com/F0hC48m.png "Error 2")

**Comment by maddinat0r** [comment]
Duplicate of #201. Please use that existing issue for any questions or discussions.
