### ISSUE TITLE
upgrade logcore requirements to be compatible with latest version too...

### ISSUE THREAD

**Issue by Zorono** [pBlueG/SA-MP-MySQL#215]

**Comment by Zorono** [comment]
and it'd be great if you upgraded samp-log plugin's logcore requirements too...(https://github.com/maddinat0r/samp-log)

**Comment by bubyygh** [comment]
This... I was just about to relaunch my server with the new discord connector features, but I can't because mysql isn't compatible with the newest log core.

**Comment by maddinat0r** [comment]
This shouldn't be an issue, because the log-core libraries used in the newest MySQL and DCC plugins are named differently.
