### ISSUE TITLE
MySQL Format (?) prints its part to the chat

### ISSUE THREAD

**Issue by samp-pinch** [pBlueG/SA-MP-MySQL#220]
I created some "macros" or better said "functions" so I can easly UPDATE data.

And when I do so, I get this in my chat:
[Image](https://i.imgur.com/cRvg3K9.png)

Here is the code:
```
sql_update_player_string(playerid, const query[], const value[], q_len = sizeof(query), v_len = sizeof(query)) // This works, ignore it
{
	mysql_format(dbHandler, query, q_len + v_len + 64, "UPDATE `players` SET `%s` = '%s' WHERE id = '%i'", query, value, playerSqlID[playerid]);
	mysql_tquery(dbHandler, query);
}

sql_update_player_int(playerid, const query[], value, q_len = sizeof(query))
{
	mysql_format(dbHandler, query, q_len + 64, "UPDATE `players` SET `%s` = '%d' WHERE id = '%i'", query, value, playerSqlID[playerid]);
	mysql_tquery(dbHandler, query);
}
```

Here is the mysql.log because other logs are empty (good):
https://pastebin.com/nteL2pAf

**Comment by maddinat0r** [comment]
This is definitely not a plugin issue. You're formatting into a const array, which you passed from somewhere, so you're probably writing into another array that's related to storing chat messages and then sending them.

**Comment by samp-pinch** [comment]
@maddinat0r problem is that I only got Auth module and I do not even have chat callback or anything like that, just sending messages like Info msg, Error msg...

**Comment by ProfessorJTJ** [comment]
Just remove const from everywhere, revert your mysql.inc include changes and do the following to the function.
const is a non editable variable, and on the other hand you're formatting an array / variable with a size that it doesn't own.

ex new string[5] = "HELLO WORLD I LOVE YOU"; [ that's what you're doing ]

`sql_update_player_string(playerid, const query[], const value[]) // This works, ignore it
{
	new dbQuery[64 + 20 + 64]; // + maximum column name length + maximum value length
	mysql_format(dbHandler, dbQuery, sizeof dbQuery, "UPDATE `players` SET `%s` = '%s' WHERE id = '%i'", query, value, playerSqlID[playerid]);
	mysql_tquery(dbHandler, dbQuery);
}

sql_update_player_int(playerid, const query[], value, q_len = sizeof(query))
{
    new dbQuery[64 + 20 + 10]; // + maximum column name length + maximum value length
	mysql_format(dbHandler, dbQuery, sizeof dbQuery, "UPDATE `players` SET `%s` = '%d' WHERE id = '%i'", query, value, playerSqlID[playerid]);
	mysql_tquery(dbHandler, dbQuery);
}`

**Comment by samp-pinch** [comment]
I. Love. You
I thought same about const!
