### ISSUE TITLE
warning 213: tag mismatch: expected tag "MySQL", but found none ("_")

### ISSUE THREAD

**Issue by iChiwi** [pBlueG/SA-MP-MySQL#223]
warning 213: tag mismatch: expected tag "MySQL", but found none ("_"), Any idea on this error?
```
mysql_format(connectionID, queryBuffer, sizeof(queryBuffer), "UPDATE users SET fishingskill = fishingskill + 1 WHERE uid = %i", PlayerInfo[playerid][pID]);
mysql_tquery(connectionID, queryBuffer);
```
It's almost on every mysql_format and tquery, I'm upgrading from 39-6 to R41-4

**Comment by maddinat0r** [comment]
MySQL handles got a `MySQL` tag in R40+, so you have to change your `connectionID` variable definition to something like
```pawn
new MySQL:connectionID;
```
