### ISSUE TITLE
Complete build instructions

### ISSUE THREAD

**Issue by Y-Less** [pBlueG/SA-MP-MySQL#239]
I was trying to build this.  I managed to figure out how to link to MySQL (by putting the root dir on the path), then it complained about samp-log-core being missing.  I've tried installing that but have no idea how or where to do so.  I'm currently trying to do it on Windows, but I'll need to do it on Linux as well eventually.  Do you have a script that can be run to install all dependencies correctly, and build the result?

**Comment by maddinat0r** [comment]
You should take a look at the CI configs for [Windows](https://github.com/pBlueG/SA-MP-MySQL/blob/master/appveyor.yml) and [Linux](https://github.com/pBlueG/SA-MP-MySQL/blob/master/.travis.yml), those should be more or less straightforward to use (you can obviously skip the test-part, i.e. the SA-MP server and PAWN compiler installation and invocation).
