### ISSUE TITLE
Please upload wiki.

### ISSUE THREAD

**Issue by sklawik** [pBlueG/SA-MP-MySQL#241]
The documentation is gone due to removal of the sa-mp wiki.

**Comment by maddinat0r** [comment]
The [GitHub wiki](https://github.com/pBlueG/SA-MP-MySQL/wiki) is editable by anyone with a GitHub account, so feel free to contribute to it.
I don't have a copy of the MySQL plugin wiki page, but I wouldn't be surprised if somebody has archived it. If so, please upload the plugin page here!

**Comment by rizlone** [comment]
> The documentation is gone due to removal of the sa-mp wiki.

[Wiki](https://github.com/pBlueG/SA-MP-MySQL/wiki) is updated

**Comment by maddinat0r** [comment]
@rizlone thanks a lot!
