### ISSUE TITLE
Detect if connection is gone

### ISSUE THREAD

**Issue by Walter-Correa** [pBlueG/SA-MP-MySQL#249]
I'm using msql_query () and the OnQueryError callback doesn't work, so I was wondering how can I create a function to detect if the connection went down at any time?

**Comment by maddinat0r** [comment]
Use `mysql_errno` to check for errors after calling `mysql_query`.

**Comment by Walter-Correa** [comment]
> Use `mysql_errno` to check for errors after calling `mysql_query`.

EDIT: **Thanks**
