### ISSUE TITLE
[FIXED] cache_get_value_int_ovrld

### ISSUE THREAD

**Issue by PutuSuhartawan** [pBlueG/SA-MP-MySQL#255]
![image](https://user-images.githubusercontent.com/71969427/113122179-f40fb180-9245-11eb-8125-e2117c09945a.png)

**Comment by Bronzal** [comment]
- cache_get_value_int(rowidx, column_index, &destination)

[plugin wiki page](https://github.com/pBlueG/SA-MP-MySQL/wiki)

**Comment by PutuSuhartawan** [comment]
**FIXED with**

```
new int_dest;
cache_get_value_index_int(3, 0, int_dest);
printf("The number stored in the fourth row and first column is '%d'.", int_dest);
```

`vehicleid = GetOwnableCarBySqlID( cache_get_value_int(idx, "owner_id", get_vehicle_data[vehicleid][V_ACTION_ID]) );
    if(vehicleid != INVALID_VEHICLE_ID)
    {
      for(slot = 0; slot < MAX_VEHICLE_TRUNK_SLOTS; slot ++)
      {
        if(GetTrunkData(vehicleid, slot, TRUNK_SQL_ID)) continue;

        cache_get_value_int(idx, "id", get_vehicle_trunk[vehicleid][slot][TRUNK_SQL_ID]);
        cache_get_value_int(idx, "item_type", get_vehicle_trunk[vehicleid][slot][TRUNK_ITEM_TYPE]);
        cache_get_value_int(idx, "amount", get_vehicle_trunk[vehicleid][slot][TRUNK_ITEM_AMOUNT]);
        cache_get_value_int(idx, "value", get_vehicle_trunk[vehicleid][slot][TRUNK_ITEM_VALUE]);`

![image](https://user-images.githubusercontent.com/71969427/113343192-139bfc80-9362-11eb-824d-b914e2a8c16e.png)
