### ISSUE TITLE
Problem when compiling on Ubuntu ARM64

### ISSUE THREAD

**Issue by lPauI** [pBlueG/SA-MP-MySQL#280]
paul@raspberrypi:~/Desktop/SA-MP-MySQL/build$ cmake ..
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MySQLCAPI: /usr/include/mysql  
-- CMake version: 3.24.2
CMake Deprecation Warning at libs/fmt/CMakeLists.txt:6 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at libs/fmt/CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0063 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Version: 4.1.0
-- Build type: 
-- Performing Test HAVE_STD_CPP11_FLAG
-- Performing Test HAVE_STD_CPP11_FLAG - Failed
-- Performing Test HAVE_STD_CPP0X_FLAG
-- Performing Test HAVE_STD_CPP0X_FLAG - Failed
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES
-- Performing Test SUPPORTS_VARIADIC_TEMPLATES - Failed
-- Performing Test SUPPORTS_INITIALIZER_LIST
-- Performing Test SUPPORTS_INITIALIZER_LIST - Failed
-- Performing Test SUPPORTS_ENUM_BASE
-- Performing Test SUPPORTS_ENUM_BASE - Failed
-- Performing Test SUPPORTS_TYPE_TRAITS
-- Performing Test SUPPORTS_TYPE_TRAITS - Failed
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Failed
-- Looking for open
-- Looking for open - not found
CMake Error at CMakeLists.txt:33 (find_package):
  Could not find a package configuration file provided by "log-core" with any
  of the following names:

    log-coreConfig.cmake
    log-core-config.cmake

  Add the installation prefix of "log-core" to CMAKE_PREFIX_PATH or set
  "log-core_DIR" to a directory containing one of the above files.  If
  "log-core" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/paul/Desktop/SA-MP-MySQL/build/CMakeFiles/CMakeOutput.log".
See also "/home/paul/Desktop/SA-MP-MySQL/build/CMakeFiles/CMakeError.log".

**Comment by zkelo** [comment]
You need to clone or download [samp-log-core](https://github.com/maddinat0r/samp-log-core) repo and then specify path to its `cmake` subfolder with option `-DCMAKE_PREFIX_PATH`

Also you may need to use these options when building: `-DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32`

**Comment by lPauI** [comment]
it worked for me to compile log-core and sudo make install after that
