### ISSUE TITLE
warning 213: tag mismatch: expected tag none ("_"), but found "MySQL"

### ISSUE THREAD

**Issue by KirovNoName** [pBlueG/SA-MP-MySQL#285]
i found this error

`warning 213: tag mismatch: expected tag none ("_"), but found "MySQL"`

`new rows = cache_get_row_count(radioConnectionID);`

**Comment by adib-yg** [comment]
You need to pass the `rows` variable to `cache_get_row_count` in MySQL R41
```pawn
new rows;
cache_get_row_count(rows);
```

or use `cache_num_rows` function
```pawn
new rows = cache_num_rows();
```

**Comment by KirovNoName** [comment]
> You need to pass the `rows` variable to `cache_get_row_count` in MySQL R41
> 
> ```pawn
> new rows;
> cache_get_row_count(rows);
> ```
> 
> or use `cache_num_rows` function
> 
> ```pawn
> new rows = cache_num_rows();
> ```

thanks
