### ISSUE TITLE
Prepared statements

### ISSUE THREAD

**Issue by maddinat0r** [pBlueG/SA-MP-MySQL#29]
I should think about adding prepared statements, would be a nice new feature in R40.

**Comment by PT-Player** [comment]
Add that we will like on SQLitei from Slice haves that.

Its an nice feature.

**Comment by Dayvison** [comment]
Really good, please add this

**Comment by pds2k12** [comment]
I'm waiting for this to happen :)

**Comment by maddinat0r** [comment]
After careful consideration (and much trial and error), I've decided to not implement prepared statements.

The problem is, that I have to thread prepared statements, or it wouldn't make any sense to implement them altogether. Threading them is presenting a big difficulty though. 
The MySQL C API expects variable addresses in order to get and/or set data (depending on the query, e.g. if you're sending a query like `INSERT INTO table VALUES (?, 'test')` and bind a variable `x` to it, the MySQL client will read `x` on statement execution). Using PAWN variable addresses directly (although probably unsafe) is possible, but very dangerous, since they will be read from/written to in another thread than the default PAWN thread (concurrent memory access = bad). 
In order to circumvent this problem, I'd have to cache all values from the PAWN thread and re-apply them on other variables previously registered to the prepared statement. Considering this example code
```pawn
new int_var;
new Stmt:stmt = mysql_stmt_create(sql, "INSERT INTO test VALUES (?, 'asdf', 3.5123)");
mysql_stmt_bind_int(stmt, 0, int); // 0 = value index

for(new i; i != 100; i++)
{
	int += i * 10;
	mysql_stmt_execute(statement);
}
```
that would mean, that I'd have to store the value of `int_var` 100 times and reapply it 100 times again. Now imagine that with even more iterations and more data (especially strings).
Caching variables is not the only problem though. Implementing that whole system correctly (background query management, result handling and re-applying to PAWN variables, destroying internal MySQL C API statement handles) is giving me a headache.

However, there is still a way to use prepared statements. MySQL supports server-side prepared statements:
```sql
PREPARE stmt FROM 'INSERT INTO test VALUES (?, ''asdf'')';
SET @a = 3;
SET @b = 4;
EXECUTE stmt1 USING @a, @b;
```
As a matter of fact, this code should also work on R39:
```pawn
new var_frmt[16];
mysql_tquery(sql, "PREPARE stmt FROM 'INSERT INTO test VALUES (?, ''asdf'', 3.142112)'");
for (new i; i != 10; i++)
{
	format(var_frmt, sizeof var_frmt, "SET @a = %d", i + 1);
    mysql_tquery(sql, var_frmt);
    mysql_tquery(sql, "EXECUTE stmt USING @a");
}
mysql_tquery(sql, "DEALLOCATE PREPARE stmt");
```

**Comment by Kar2k** [comment]
You can take a look at how Slice implemented prepared statements for SQLite. http://forum.sa-mp.com/showthread.php?t=303682&highlight=sqlitei

**Comment by PT-Player** [comment]
An guy on Portuguese board made this:

**Comment by maddinat0r** [comment]
Both includes (I guess the second link @PT-Player provided too, but the pastebin link in that thread is invalid) are emulating prepared statements. They basically do the same thing the ORM system does: collect variables, generate a query string and send it. Fact is, they always send a whole query to the server.
Real prepared statements work like that: You send the prepared statement to the server, the server, well, prepares that query and then you just send the appropriate values for the query to use. So you never send a whole query with data, and that is exactly the point in prepared statements: Split query statement and real data apart, so that the server won't have to parse the query every time it's sent.

**Comment by maddinat0r** [comment]
I also don't see much sense in adding a similar system to the plugin. If someone really wants something like this, they'd have to create this by themselves (or even better, using server-side prepared statements the MySQL server supports).

**Comment by PT-Player** [comment]
He is doing that now using GitHub take an look if you want now: https://github.com/Dayvison/MySQL-Stataments

**Comment by maddinat0r** [comment]
Yes, as I thought, this is the same as Slice' prepared statements include (judging by the code it probably IS Slice' include, only adapted to be used with the MySQL plugin).

**Comment by PT-Player** [comment]
Yes that is true @maddinat0r.
