### ISSUE TITLE
Problem with tquery - mixing callbacks

### ISSUE THREAD

**Issue by Damianoseczek** [pBlueG/SA-MP-MySQL#49]
Hi.
I have problem with plugin. When I'm using mysql_tquery I have something like 'mixing query callbacks'. When the count of players is more than 30/40 there is something weird. Accounts are mixing together. I don't know why this happens. When (now) I replaced all tquery with pquery (I know that pquery need to be fixed) I don't have any mixing of accounts. 

The other thing is that when I have more players there are big lags on server. I don't know why. Maybe some lagger? Maybe mysql? 
I don't think that this is problem in my gamemode, because sometimes there is lag when on my server are less than 10 players.

Waiting for answer.

**Comment by Damianoseczek** [comment]
Okay. I have tested speed of queries. MySQL and SA-MP are on the same machine. 
After debugging ONLY login query (checks for account, if exists then I'm getting datas).
Speed is from 69ms to 561ms (only once I had 561ms). 6 times -> 300-400ms
The rest is from 70-150ms

I don't think that is fast, but this scores aren't bad, hm?

**Comment by maddinat0r** [comment]
The fact that `mysql_pquery` is in most cases faster than `mysql_tquery` is no secret. Care to share some of your code? E.g. all player-login related queries and their result callbacks.
