### ISSUE TITLE
problem with get Chinses character content.

### ISSUE THREAD

**Issue by VivianKris** [pBlueG/SA-MP-MySQL#50]
Hello guys, just got a character problem.
and I stil think the problem is charaset with PAWN and not a MySQL falut.

in my Mysql table, there is a row named "userName" and saving string.
my filed is just like "金正恩"   (some Chinese characters just like "Kim jong un")

```
    cache_get_field_content(0, "userName", userName, 1, MAX_CHINSES_NAME);
    printf("%s", userName);

```

it should print  "金正恩"

but it output "?????"

Who can explain that problem or just give me a referance?

Thank you.

**Comment by maddinat0r** [comment]
You need to set the correct character set via `mysql_set_charset`.
Apart from that, you'll need to enable support for your locale in your OS of course.
