### ISSUE TITLE
boost::thread_resource_error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by habl** [pBlueG/SA-MP-MySQL#51]
Hi,

I'm trying to make your plugin working on Debian 7 64bit, but can't get it to work. I get an error from the boost library or something, as soon as I start connecting to MySQL (see below). The plugin does load though.
I'm using mysql_static.so, mysql client version 5.6.12. Also tried mysql_5.5.so, and compiling the plugin myself, but I can't get it to work.

I had a test server running on a Windows 7 environment aswell with the same code, where it worked fine.

I can't add debug code since the server dies after mysql_connect. Do you have any idea what's wrong?

$ ./samp03svr

Started server on port: 7789, with maxplayers: 30 lanmode is OFF.

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
  what():  boost::thread_resource_error: Resource temporarily unavailable
Aborted

Code using:

initMysql()
{
	print("Connecting to MySQL...");
	MySQL = mysql_connect("127.0.0.1", "samp", "samp", "password", 3306, true);
	
	new error = mysql_errno(MySQL);
	new errorString[100];
	
	format(errorString, sizeof (errorString), "Connect: %i", error);
	
	print(errorString);
}

**Comment by maddinat0r** [comment]
Looks like your machine doesn't have enough resources to create the internal MySQL threads. Try closing some programs and deactivate the connection pool (set `pool_size` in `mysql_connect` to `0`) if you don't use parallel queries (`mysql_pquery`).

**Comment by habl** [comment]
Setting the pool_size to 0 seems to have fixed it.
Got some other problems now, but don't have time to debug now.

Thanks for your help! :)

**Comment by maddinat0r** [comment]
No problem.
