### ISSUE TITLE
The problem with the version

### ISSUE THREAD

**Issue by Daewo147** [pBlueG/SA-MP-MySQL#52]
hello i have a problem so he wants to update the script with the current versions RC7 but when I compile errors , but do not know how to update these functions (?)
undefined symbol "mysql_ping"
undefined symbol "mysql_affected_rows"
undefined symbol "mysql_insert_id"

**Comment by maddinat0r** [comment]
There are like thousands of other threads like this in the official SA-MP forum, so search there for a solution. This is the wrong place for this kind of question.
