### ISSUE TITLE
onqueryerror not called.

### ISSUE THREAD

**Issue by JernejL** [pBlueG/SA-MP-MySQL#59]
select report_create_new(15234077, 15234075, 'tasty test')

A function containing call to invalid function, error 1305.. onqueryerror was never called. 
 
Error Code: 1305. FUNCTION cam_partyserver.insert_id does not exist

**Comment by maddinat0r** [comment]
Are you using R39-3?

**Comment by JernejL** [comment]
Apparently not.. seems like i forgot to replace the .so, this was on R35.
