### ISSUE TITLE
Random "Lost connection to MySQL server during query" without any cause

### ISSUE THREAD

**Issue by JernejL** [pBlueG/SA-MP-MySQL#60]
plugin.mysql: R39-3 successfully loaded.
 
There is no reason for mysql plugin to lose connections, i've been running it for literally years without a issue and this has now started happening, i use Tquery only and every mysql_connect call has reconnect parameter set to true. 
 
The only thing that changed recently is, that i had to disable crashdetect for a while. 
 
Maybe this is an effect of mysql plugin threads crashing or something? 
 
mysql_connect(SQL_HOST, SQL_USER, SQL_DB, SQL_PASS, SQL_PORT, true);

**Comment by JernejL** [comment]
I did my grep-ing of logs.. and this has only started to happen after switching from R35 to R39-3. 
 
There is NO reason for connection to have been closed, my connections are permanent. 
 
I did my best research and there is nothing external closing the connection than plugin itself.

**Comment by maddinat0r** [comment]
Could you reproduce this with debug logging enabled and share your log output here?

**Comment by JernejL** [comment]
84692813-[11:01:02] [DEBUG] mysql_tquery - connection: 1, query: "update ", callback: "JustDecrementQueryCounter", format: "i"
84692977-[11:01:02] [DEBUG] mysql_tquery - connection: 1, query: "update ", callback: "JustDecrementQueryCounter", format: "i"
84693152-[11:01:02] [DEBUG] mysql_tquery - connection: 1, query: "update ", callback: "NS_SaveAccount", format: "ii"
84693317-[11:01:02] [DEBUG] mysql_unprocessed_queries - connection: 1
84693378-[11:01:02] [DEBUG] mysql_tquery - connection: 1, query: "SELECT ", callback: "ET_GetCmds", format: "(null)"
84693543-[11:01:02] [DEBUG] CMySQLQuery::Execute[JustDecrementQueryCounter] - query was successfully executed within 858.236 milliseconds
84693672-[11:01:02] [DEBUG] CMySQLResult::CMySQLResult() - constructor called
84693741-[11:01:02] [DEBUG] CMySQLQuery::Execute[JustDecrementQueryCounter] - starting query execution
84693835-[11:01:02] [DEBUG] Calling callback "JustDecrementQueryCounter"..
84693901-[11:01:02] [DEBUG] CMySQLResult::~CMySQLResult() - deconstructor called
84693973:[11:01:03] [ERROR] CMySQLQuery::Execute[JustDecrementQueryCounter] - (error #2013) Lost connection to MySQL server during query
84694101-[11:01:03] [DEBUG] CMySQLQuery::Execute[JustDecrementQueryCounter] - error will be triggered in OnQueryError
84694210-[11:01:03] [DEBUG] CMySQLQuery::Execute[JustDecrementQueryCounter] - starting query execution
84694304-[11:01:03] [DEBUG] mysql_tquery - connection: 1, query: "update ", callback: "JustDecrementQueryCounter", format: "i"
84694479-[11:01:03] [DEBUG] mysql_tquery - connection: 1, query: "update ", callback: "JustDecrementQueryCounter", format: "i"
84694654-[11:01:03] [DEBUG] mysql_tquery - connection: 1, query: "insert ", callback: "spec_logenterspecid", format: "ii"
84694824-[11:01:03] [DEBUG] Calling callback "OnQueryError"..
84694877-[11:01:03] [DEBUG] mysql_reconnect - connection: 1
84694928-[11:01:03] [DEBUG] CMySQLConnection::Disconnect - connection was closed
84695000-[11:01:03] [DEBUG] CMySQLConnection::Connect - establishing connection to database...
84695086-[11:01:03] [DEBUG] CMySQLConnection::Connect - connection was successful

There is nothing there, these disconnects seem to be caused somehow by the plugin internally and there id no indication on what would do this. 
 
Downgrading plugin to R34 had fixed it for me.

**Comment by JernejL** [comment]
I guess this is something caused by pquery implementation. 
All my queries are tquery type and the server runs fine for a while.. sometimes even hours before this starts to happen and connectiony simply die.

**Comment by maddinat0r** [comment]
Did you set the `pool_size` parameter in `mysql_connect` to zero?

**Comment by JernejL** [comment]
I've left it at default value. Later i tried changing it to "1". 

Both had same issue,

**Comment by maddinat0r** [comment]
Did you actually tried to set it to zero (0) like this
```pawn
mysql_connect("hostname", "username", "database", "password", .pool_size = 0);
```
?

**Comment by JernejL** [comment]
No.. As there was nothing documented on wiki about this parameter affecting Tqueries and i do not use any pquery. 
 
See: 
http://wiki.sa-mp.com/wiki/MySQL/R33#mysql_connect 
 
I will try again with this set to 0, but still - this should not affect tquery.

**Comment by maddinat0r** [comment]
Any updates on this yet @JernejL?

**Comment by JernejL** [comment]
Not yet - i was not able to analyze this again, but i will once i update my server to 0.3.7 (which is today)

**Comment by JernejL** [comment]
Seems like setting pool size to 0 makes it function again, at least on windows in r39-3.

**Comment by JernejL** [comment]
Doing new tests.. still have issues with connections - can't figure this out.. I will prepare a in-depth report for you.

**Comment by maddinat0r** [comment]
Maybe your MySQL server allows only a very limited amount of concurrent open connections (I'm talking about the MySQL server here, not the SA-MP server; thus a connection from anywhere like a user control panel or panels like phpMyAdmin count too) and closes other connections instead.

It's unlikely that this is a plugin problem, since you're the only one reporting this type of problem and the effective difference between R35 and R39-3 is the higher amount of connections to the MySQL server.

**Comment by d4rkuzs** [comment]
I have this issue too, it happens when the server stops doing sql operations (after certain time of 'inactivity'). But, after the operation fails, the samp server reconnects to the sql server and all sql operations work again.
