### ISSUE TITLE
mysql_unprocessed_queries

### ISSUE THREAD

**Issue by JernejL** [pBlueG/SA-MP-MySQL#63]
This function is currently de-implemented? 
 
https://github.com/pBlueG/SA-MP-MySQL/blob/5ad053c20eacb5eb80f7677d2a00547c9416b4fd/src/CScripting.cpp#L163

**Comment by Mellnik** [comment]
Wrong branch you are. This is R39-3: https://github.com/pBlueG/SA-MP-MySQL/tree/issue-54

**Comment by JernejL** [comment]
funny.. that's the only time it finds anything in source when i search for "mysql_unprocessed_queries".. i'm just wondering to see if mysql_unprocessed_queries could be causing any kind of mutex lock scenarios in the pawn thread.

**Comment by maddinat0r** [comment]
[mysql_unprocessed_queries](https://github.com/pBlueG/SA-MP-MySQL/blob/R39-3/src/CScripting.cpp#L780-L790) uses `GetUnprocessedQueryCount`, which only [returns a value of a variable](https://github.com/pBlueG/SA-MP-MySQL/blob/R39-3/src/CMySQLHandle.h#L63). No mutexes here.
