### ISSUE TITLE
Check for table if exists?

### ISSUE THREAD

**Issue by BulgEdition** [pBlueG/SA-MP-MySQL#65]
Hey is there any way to check if table is existing in database?
I want to make if table "some name" is not exists to make a new one and if exists to print debug message in console.

**Comment by JernejL** [comment]
"create table if not exists" syntax.. 
 
http://dev.mysql.com/doc/refman/5.1/en/create-table.html
 
This is part of mysql and nothing to do with plugin.

**Comment by BulgEdition** [comment]
Yea I know for that but I don't know how to set the debug messages when creates a new and when is using one? How???

**Comment by maddinat0r** [comment]
Use unthreaded queries.
