### ISSUE TITLE
mysql_query InnoDB row lock problem.

### ISSUE THREAD

**Issue by zndn1997** [pBlueG/SA-MP-MySQL#67]
My server is separate MySQL Server and SA-MP Dedicated Server.

if I use InnoDB engine and mix use mysql_query and mysql_tquery to mode, Plugin often output error.

"2013: Lost connection to MySQL server during query"
or
"1205: Lock wait timeout exceeded; try restarting transaction"

if I convert all of mysql_query to mysql_tquery, This problem is correctly removed.\

I think mysql_query is NOT freezing at during TRANSACTION complete. That means row is still locked, but mysql_query freezing stop and run mode.
So I think mysql_query is only freezing while query send is not successful.

I want server still freezing by mysql_query for about when transaction is fully complete.

**Comment by maddinat0r** [comment]
I don't think I really understood your problem. Could you post a small piece of code to reproduce this?

**Comment by zndn1997** [comment]
Ok.

public Example(playerid)
{
        new chString[145];
        GetPlayerName(playerid, chString, 145);
        format(chString, 145, "INSERT INTO userdata (name) VALUES('%s')", chString);
        new Cache: cResult = mysql_query(MySQL, chString);
        new rows = cache_affected_rows();
        cache_delete(cResult);
        if(rows == 0) printf("[MySQL] Account INSERT query error.");
       
        OnPlayerSave(playerid);
        return 1;
}
 
public OnPlayerSave(playerid)
{
        #define CHAR_LENGTH 7000
        new chString[CHAR_LENGTH];
        GetPlayerName(playerid, chString, CHAR_LENGTH);
        format(chString, CHAR_LENGTH, "UPDATE userdata SET bla=%d,bla=%.4f,bla='%s' WHERE name='%s'", bla, bla, bla, chString);
        mysql_tquery(MySQL, chString, "Invalid");
        #undef CHAR_LENGTH
}
 
public Invalid(playerid) // It's use to debugging
{
        return 1;
}
 
public OnQueryError(errorid, error[], callback[], query[])
{
        printf("[MySQL Error] %d: %s (%s)", errorid, error, callback);
        /*Server log writed when OnPlayerSave call before Example was called.
        Error result is:
       
        "1205: Lock wait timeout exceeded; try restarting transaction."
 
        or
 
        "2013: Lost connection to MySQL server during query."
 
 
        So, This error cause mysql_query is not detect row unlock of INSERT query.*/
        return 1;
}

**Comment by maddinat0r** [comment]
Could you check your `mysql_log.txt` if there's any error reported for the INSERT query? You should also check the output of `mysql_errno()` after executing unthreaded queries (`mysql_query()`), probably like this:
```pawn
public Example(playerid)
{
        new chString[145];
        GetPlayerName(playerid, chString, 145);
        format(chString, 145, "INSERT INTO userdata (name) VALUES('%s')", chString);
        mysql_query(MySQL, chString, false);
        if(mysql_errno(MySQL)) 
                printf("[MySQL] Account INSERT query error (error %d).", mysql_errno(MySQL));

        OnPlayerSave(playerid);
        return 1;
}
```

**Comment by zndn1997** [comment]
no, It's not INSERT query error. server is not yet row unlock after mysql_query INSERT, But server resume proccessing next script.

**Comment by maddinat0r** [comment]
Something has to cause the row locking, and I doubt that this small INSERT query does this. Maybe there's some web-panel accessing that table and updating tons of information? Or maybe you're updating user information periodically in your script, sending a very long UPDATE query?

You could also try executing `SHOW ENGINE INNODB STATUS` after your suspected INSERT query and in `OnQueryError` and print/write the result to the console/a file for further information.
