### ISSUE TITLE
Server crash on orm var load returning NULL.

### ISSUE THREAD

**Issue by startukk** [pBlueG/SA-MP-MySQL#70]
when you add an orm var and then try to apply all the vars from the database via orm_select/orm_load, if the field data returned for that var is NULL from the database, it will crash the server.

edit: I might be horribly wrong, but thats atleast what kept crashing my server.

**Comment by maddinat0r** [comment]
Duplicate: issue #68 
I'll release an update (R39-4) sooner or later, so hold on a little while.
