### ISSUE TITLE
tinyint problem

### ISSUE THREAD

**Issue by Cypka** [pBlueG/SA-MP-MySQL#75]
Using tinyint in table structure gives me a mysql syntax error. I have tried using TINYINT and it worked fine. Is this a problem or it's mean to be like that?

int can be used as INT or int...

**Comment by Kar2k** [comment]
Linux is case sensitive and Windows is incase sensitive. Maybe this is your issue?

**Comment by maddinat0r** [comment]
MySQL keywords are case-insensitive, so `tinyint` should've worked fine. Maybe you just mistyped it by accident?

**Comment by Cypka** [comment]
It seems to be working fine now. I have deleted the old query that I've been using and can't really remember how I had it structured. 

I guess you can close this issue, sorry for spending your time tho.

**Comment by maddinat0r** [comment]
No problem :smile:
