### ISSUE TITLE
mysql_c(allback)query

### ISSUE THREAD

**Issue by IstuntmanI** [pBlueG/SA-MP-MySQL#76]
I thought that it would be great to have a mysql_cquery function, which instead of calling the codes right after mysql_query, it could execute them in a callback, just like mysql_tquery does, but without the threading.

The best example I can think for it is under OnGameModeInit, so instead of adding every code for every loading there, we can have callbacks for all.

**Comment by maddinat0r** [comment]
Doesn't really make sense to me. Where's the difference to this:
```pawn
public OnGameModeInit()
{
	new Cache:res = mysql_query(sql, "SELECT * FROM stuff");
	OnSystemInitialize();
	cache_delete(res);
	return 1;
}

public OnSystemInitialize()
{
	// cache_get_row
	// ...
	return 1;
}
```
?

If you really need such a function for some reason, here's a macro:
```pawn
ReturnFalse()
{
	return 0;
}
#define mysql_cquery(%0,%1,"%2",%3) \
do { \
	new Cache:__res = mysql_query(%0, %1); \
	%2(%3); \
	cache_delete(__res); \
} while(ReturnFalse())

forward OnSystemInit(int, Float:flt);
public OnSystemInit(int, Float:flt)
{
	//do stuff
	return 1;
}

public OnGameModeInit()
{
	new MySQL:sql = MySQL:1;
	mysql_cquery(sql, "SELECT * FROM stuff", "OnSystemInit", 3, 4.412);
	return 1;
}

```

**Comment by IstuntmanI** [comment]
Aw, I didn't thought of this:
>new Cache:res = mysql_query(sql, "SELECT * FROM stuff");
OnSystemInitialize();
cache_delete(res);

My bad. :D
