### ISSUE TITLE
mysql_stat huge amount bug ?

### ISSUE THREAD

**Issue by IstuntmanI** [pBlueG/SA-MP-MySQL#77]
![screenshot_1](https://cloud.githubusercontent.com/assets/6208948/12888179/6993e9b4-ce81-11e5-8405-b6f44732b070.png)

As you can see, "Queries per second average" is displaying a ridiculous amount, which isn't even possible, and that amount is always increasing with something like 0.02 or more. The "Questions" increase with that amount almost everytime, as I can see. If that would be true, the "Unprocessed queries" for sure wouldn't be 0 always, because you can't execute ~1431 queries per second and have them processed instantly, the server would even hang. I really think this is a bug, there's no chance this could happen while the server is running smoothly.

Or my definition of "query" is wrong ? A query is the thing you send with mysql_pquery, mysql_tquery, mysql_query. "Questions" are the number of queries sent since the server was started, right ?

**Comment by maddinat0r** [comment]
You're retrieving the status of the MySQL server here. I guess you're using a hosted MySQL database by some bigger provider, so these readings actually can be plausible.

**Comment by IstuntmanI** [comment]
Yes, I do. It's weird that the MySQL server reports this to all clients. I thought that this is per-connection, I thought it was weird why on my localhost it was working fine and on the host not, I also thought of what you said, but I wasn't sure about that.

Can you make something like per-connection ?

**Comment by maddinat0r** [comment]
I could, but that wouldn't really be a useful feature (more likely a complicated one) and I'm already way behind schedule to release R40. 
`mysql_stat` was made simply because there is exactly that same function in the MySQL C API, thus making it pretty easy to just wrap it around with some code and make it available as a PAWN native.

**Comment by IstuntmanI** [comment]
If it is complicated, then don't add it, it isn't really needed, it was just nice to see the statistics. And yes, I know that you are way behind the schedule to release it. :c
I already thought that it might be offered by MySQL.

Well, I close this.
