### ISSUE TITLE
Get field type

### ISSUE THREAD

**Issue by ch3rkasov** [pBlueG/SA-MP-MySQL#79]
Please add this feature.

**Comment by maddinat0r** [comment]
Out of curiosity: what do you need that information for?

**Comment by ch3rkasov** [comment]
I use PVar's to store player data. I can identify the type of a PVar by using the function while saving, but i can't identify the type of a field while loading
http://pastebin.com/D99LSh15

**Comment by maddinat0r** [comment]
Ha, neat! I'll add a `cache_get_field` function, expect it in R40.
