### ISSUE TITLE
mysql_connect_file

### ISSUE THREAD

**Issue by KennyDalglish** [pBlueG/SA-MP-MySQL#82]
Hi. Function mysql_connect_file there in [source plugins](https://github.com/pBlueG/SA-MP-MySQL/blob/master/src/CHandle.cpp#L157-L274), but not declared in [release plugins](https://github.com/pBlueG/SA-MP-MySQL/releases/tag/R39-4).
Screen: [click](http://i.imgur.com/LwqbeZ4.png)
Even if declare a native function:
`native MySQL:mysql_connect_file(const file_name[] = "mysql.ini");`
That is still the server will report an error.
Property , the question : What are the reasons the function is removed from the plug-in ? And whether it will in release? 
Or just to compile the plugin itself ?
Thank you in advance.

P.S: I'm sorry for my English Language

**Comment by maddinat0r** [comment]
The source code on the master branch represents the upcoming version R40. The R39 releases are on the [`issue-54` branch](https://github.com/pBlueG/SA-MP-MySQL/tree/issue-54) (I know, weird name, but that's how it is).
Thus that new native is one among many, which will be available in R40.
