### ISSUE TITLE
Travis downloadable artifacts ?

### ISSUE THREAD

**Issue by IstuntmanI** [pBlueG/SA-MP-MySQL#84]
I don't know if this is what I want (.so from travis to be downloadable on the travis-ci site), or if it would work fine, but there it is: https://docs.travis-ci.com/user/uploading-artifacts/ . As I understood, it would make the generated .so to be available for dowload on their site.

**Comment by maddinat0r** [comment]
Not on their site, but on an AWS server I have to specify. 
There is another way of uploading build artifacts from TravisCI directly to Github though, but I'd have to pollute the releases page for this (which I don't really want to).
If you really want to test or play around with the latest R40 build, you can always PM me on the official SA-MP forum and ask for one.
