### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by spmn** [pBlueG/SA-MP-MySQL#88]
Does callback order depend on the order of ``mysql_tquery``s, or are there any other variables to depend on?

Eg: Let's say that we retrieve data from a MySQL database using the following code:
```
main()
{
	mysql_tquery(1, "SELECT * from table1", "f1", "");
	mysql_tquery(1, "SELECT * from table2", "f2", "");
	mysql_tquery(1, "SELECT * from table3", "f3", "");
}

public f1() 
{
	printf("f1 called);
}

public f2() 
{
	printf("f2 called);
}

public f3() 
{
	printf("f3 called);
}
```

Callback order will ALWAYS be f1 -> f2 -> f3 or it may vary?

**Comment by maddinat0r** [comment]
Queries (and their corresponding result callbacks) fired by `mysql_tquery` are always guaranteed to be executed in the order they're called.
So yes, in your case the callback order will always be f1 -> f2 -> f3.

**Comment by spmn** [comment]
Ok, thank you!
