### ISSUE TITLE
Utf8 Create Table

### ISSUE THREAD

**Issue by MaxAndolini** [pBlueG/SA-MP-MySQL#89]
How to create table with uft8?

**Comment by Jeroen52** [comment]
This sounds more like a MySQL issue instead of a MySQL plugin issue.

**Comment by MaxAndolini** [comment]
I dont know. I am create table in pawn but characters are distorted.

**Comment by Jeroen52** [comment]
Can you show what the code is and what the result is?

**Comment by MaxAndolini** [comment]
Normal: Ağrı
Result: Aðrý

**Comment by Jeroen52** [comment]
As far as I am aware, SAMP only supports ASCII encoding.

**Comment by MaxAndolini** [comment]
I am know this. But my problem is mysql create table isnt utf8.

**Comment by Jeroen52** [comment]
So do you have a problem at creating the MySQL table in UTF-8 or insert UTF-8 info in the MySQL table?

**Comment by MaxAndolini** [comment]
Yea my problem Create table :+1:

**Comment by Jeroen52** [comment]
I think that it is a generic MySQL question then, and not something specific about this plugin.
Try to add this at the end of the query.
`CHARACTER SET=utf8`
Here is an example.
`CREATE TABLE `temp`.`testTable` ( `id` INT NOT NULL , `name` INT NOT NULL , `test` INT NOT NULL , `abc` INT NOT NULL ) ENGINE = InnoDB CHARACTER SET=utf8`

**Comment by MaxAndolini** [comment]
I am using Easy MySQL include. How can I do that?

http://forum.sa-mp.com/showthread.php?t=590310

**Comment by Jeroen52** [comment]
I do not use Easy MySQL and have no experience with it, if you need help with MySQL while using that include please seek help at their forum thread. You can always wait here but I am unsure if those guys follow the issues here.

**Comment by MaxAndolini** [comment]
Thank you for trying to help :)

**Comment by maddinat0r** [comment]
Thanks @Jeroen52 for your help! I guess that I can close this now.

**Comment by MaxAndolini** [comment]
@maddinat0r its not solve?

**Comment by Jeroen52** [comment]
I think that this is not a plugin issue but a question about an include which happens to have this plugin as a dependency.

**Comment by MaxAndolini** [comment]
Only say to me how to create table utf8 with query?

**Comment by Jeroen52** [comment]
Well, you use a regular `CREATE TABLE` query but with a `CHARACTER SET=utf8` at the end.

**Comment by MaxAndolini** [comment]
Okey im try.

**Comment by MaxAndolini** [comment]
(error #1064) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET=utf8 )' at line 1

**Comment by Jeroen52** [comment]
Can you show the entire query?

**Comment by MaxAndolini** [comment]
This end. strcat(SQL::upd_query[handle], "CHARACTER SET=utf8 );");

**Comment by Jeroen52** [comment]
Try the following: `strcat(SQL::upd_query[handle], ") CHARACTER SET=utf8;");`
If that doesn't work, show the entire MySQL query.

**Comment by MaxAndolini** [comment]
@Jeroen52 (error #1064) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET=utf8' at line 1 :(

**Comment by Jeroen52** [comment]
Can you show the entire MySQL query? And not only the end.

**Comment by MaxAndolini** [comment]
Thats here.

https://github.com/MaxAndolini/EasyMySQL/blob/master/easy-mysql.inc

Line: 1521

And CreateTable Callback.

**Comment by Jeroen52** [comment]
You should really ask this question in the easy-mysql thread.

**Comment by MaxAndolini** [comment]
No one interested in the thread.

**Comment by Jeroen52** [comment]
And I have no knowledge about easy-mysql, so I should shut my mouth.
I hope that you can resolve this issue, and please do state the answer here for future references.

**Comment by MaxAndolini** [comment]
Thank you. I am waiting :'(

**Comment by MaxAndolini** [comment]
Solved. Closed.
