### ISSUE TITLE
Medusa float

### ISSUE THREAD

**Issue by Misiur** [pBlueG/SA-MP-MySQL#90]
```pawn
new dbhandle;
EstablishConnection(dbhandle);

new string[128];
new Float:medusa = -9.170000;
printf("%f", medusa);
mysql_format(dbhandle, string, sizeof string, "%.2f", medusa);
print(string);
format(string, sizeof string, "%.2f", medusa);
print(string);
```

```
[19:05:38] -9.170000
[19:05:38] -9..70
[19:05:38] -9.17
```

I caught that in the wild causing me query errors. Usually `%.2f` works fine, just this error caught my eye

**Comment by Misiur** [comment]
If that changes anything, I'm running MariaDB

**Comment by Misiur** [comment]
https://github.com/pBlueG/SA-MP-MySQL/blob/8a4dc482ea66a33d0ff99b1598c8f897bf35768b/src/natives.cpp#L996 this is only instance adding dots that I can see

**Comment by Misiur** [comment]
After a little bit of investigation I discovered that it happens for number such as -9, -99, -999, etc. with fraction part other than 0, so -9.01, etc.

**Comment by maddinat0r** [comment]
Are you using R39 or R40?

**Comment by Misiur** [comment]
R39-4

**Comment by maddinat0r** [comment]
Yep, that's definitely a bug.
