### ISSUE TITLE
More meaningful timestamp in logs

### ISSUE THREAD

**Issue by westingham** [pBlueG/SA-MP-MySQL#92]
Currently the logfile only shows the hour/minute/second (unless I've missed an option somewhere) the log entry was recorded. Would it be possible to have the year/month/day as well? This would greatly assist in looking back through the logfile and trying to track down an issue.

Thank you!

**Comment by maddinat0r** [comment]
Starting with R40, the log time formatting is entirely configurable through the `logtimeformat` variable in the server.cfg file. 
It is not that way in R39 though and having the date in the log file is quite reasonable, so I've added it as you requested (cdf5446a305fd72a8d91c8c2e6df4b069697ee58).
