### ISSUE TITLE
Return of wrong formatting

### ISSUE THREAD

**Issue by Misiur** [pBlueG/SA-MP-MySQL#96]
#90 is back 

```pawn
new string[32];
new Float:medusa = -0.44;
printf("%.2f", medusa);
mysql_format(dbhandle, string, sizeof string, "%.2f", medusa);
print(string);
```

(I've seen you used different format method for R40, sorry for those issues)

**Comment by maddinat0r** [comment]
Argh, `mysql_format` is killing me.
Thanks for reporting though, the fewer bugs the better!

**Comment by Jeroen52** [comment]
@maddinat0r You could say that it is making you madd.
