### ISSUE TITLE
mysql_set_charset | UTF8 | Russian language

### ISSUE THREAD

**Issue by KrYpToDeN** [pBlueG/SA-MP-MySQL#97]
Hello.

Could you help me, please.
Last year i used 'CP1251 General CI' charset.
Now i decide to try UTF8 general ci (i need it).

I starting my server - it's all rights in the beginning of server work.
It works 10, maybe 12 hours without restart and if i update something in my MySQL Database, my russian language can be - "?????".

I will repeat: "it will happen after some hours".

Nothing change with charset during server work.
Only on the starting server.

I think, that maybe i did some mistakes.

`mysql_set_charset("utf8");` - don't work. I get - "????" all time.

`mysql_query(MySQL, "SET NAMES utf8 COLLATE utf8_unicode_ci");
 mysql_query(MySQL, "set character_set_connection=utf8");` - work good. But not very long time.

**Comment by KrYpToDeN** [comment]
help me, please.

**Comment by maddinat0r** [comment]
Setting the character set through a query will give you absolutely _nothing_ if you're only using threaded/parallel queries. You **have** to use `mysql_set_charset` for it to work properly.

**Comment by KrYpToDeN** [comment]
I just tried `mysql_set_charset("utf8_general_ci");`, but after 12 or more hours, SELECT and UPDATE table returned '??????' (not Russian Text). During first 12 or a bit more hours - it's ok.

**Comment by maddinat0r** [comment]
Did you had any disconnects to your MySQL server? The character set obviously resets when (re-)connecting to the server.

**Comment by KrYpToDeN** [comment]
No. No crashes, no disconnects.

I just look at my test server. It's 11 hours after my last post (i did restart 11 hours ago).
I enter into my game server account. And look at my name on Russian language. It's '??????'. It's after  'SELECT....' function(operator). (I don't know how to call it).

But if i restart my server now and update my name, and also reconnect to server, it will be ok. But only some hours.

**Comment by maddinat0r** [comment]
Well, something has to cause this. Check the MySQL plugin log, check the MySQL server log. There has to be something hinting at the problem.

**Comment by KrYpToDeN** [comment]
Oh. After i did, what you said with charset:
`mysql_set_charset("utf8_general_ci");`
I got this mistake:

> [15:00:39] [ERROR] CMySQLConnection::SetCharset - error 2019: Can't initialize character set utf8_general_ci (path: /usr/share/mysql/charsets/)

But why? MySQL DataBase has this charset in all tables, settings.

**Comment by maddinat0r** [comment]
That's because you're using the charset collation, not the actual charset, hence why it doesn't exist.
Just use `mysql_set_charset("utf8");`.

**Comment by KrYpToDeN** [comment]
ok. I will try it now and write you later.
http://wiki.sa-mp.com/wiki/MySQL/R33#mysql_set_charset
Check it, please. Your example.

**Comment by KrYpToDeN** [comment]
i tried it now, and another mistake.
When server is starting, it loads all pickups, words and etc from DataBase. Now after restart i have ??/????? and etc. It's on my screen.
![sa-mp-008](https://cloud.githubusercontent.com/assets/10742701/15574964/c7f283aa-2393-11e6-906c-200840a6e15a.png)

And also my DataBase structure (this table).
![default](https://cloud.githubusercontent.com/assets/10742701/15575005/fb506eec-2393-11e6-81bf-7ddf0630acd3.png)

**Comment by KrYpToDeN** [comment]
Do you have any ideas?

**Comment by maddinat0r** [comment]
Fixed the example in the wiki.
Are there still any errors in the MySQL plugin log?

**Comment by KrYpToDeN** [comment]
No, nothing..(

**Comment by KrYpToDeN** [comment]
I just check it on local MySQL server(my computer). The problem is the same.
`mysql_set_charset("utf8");.` doesn't work. It shows me information how on the picture.

**Comment by maddinat0r** [comment]
Are you sure the string data in your table is actually saved as UTF8 text?

**Comment by KrYpToDeN** [comment]
I think so, but i'm not sure.

Do you know, can i check it somehow? Or resave it quickly?

**Comment by maddinat0r** [comment]
Try creating a new entry from within the gamemode with the charset set to UTF8 and check if it displays and/or loads correctly afterwards.

**Comment by stabker** [comment]
Maybe this is causing the problem? http://forum.sa-mp.com/showthread.php?p=3082072#post3082072

**Comment by KrYpToDeN** [comment]
maddinat0r, i think that the problem was because tables and information maybe was created in CP1251. I think so, because i change it to CP1251 and it's all right.

Thank you for your help) I will close this issue.
