### ISSUE TITLE
mysql_tquery_file

### ISSUE THREAD

**Issue by maddinat0r** [pBlueG/SA-MP-MySQL#99]
Gotta implement that. Have to figure out if reading the file should be done in an extra thread and if yes, how these thread(s) are handled (thread pool, single thread with read queue, always new thread?).
File parsing has to be done before actually sending queries, to know which query is the last and call a result callback accordingly.
Result storing has also to be considered.

**Comment by B3LlAT0R** [comment]
mysql_tquery_file() is this safe before attack injection sql?
and could you give me a correct example about mysql_tquery_file (connect, "query.sql", CALLBACK, CONSTAN can I place mysql_format in CALLBACK and a variable in CONSTAN? i know mysql_format is good anti injection sql but i dont sure.

**Comment by maddinat0r** [comment]
`mysql_tquery_file` has exactly the same syntax as `mysql_tquery`, with the only difference that you pass a file path to your SQL file to `mysql_tquery_file` instead of a query string.
`mysql_tquery_file` only parses and executes queries from the file you specified. How you formulate those queries is up to you.

**Comment by B3LlAT0R** [comment]
Yes i see that. But with mysql_tquery i put the variant with mysql_format. Example:

new query[122];
mysql_format(hnd, query, sizeof query, "UPDATE ´samp´ SET ´money´ = %d WHERE ´ID´ LIMIT 1), player[playerid][money]);
mysql_tquery(hnd, query);

and //mysql_tquery_file() i dont know how used.

i search and you repository Examples. but not find that. If not problem help me please.

**Comment by maddinat0r** [comment]
`mysql_format` is for formatting strings, usually SQL queries. There is no real use for that function in context with `mysql_tquery_file`.
Your example usage of `mysql_tquery_file` is absolutely fine. That call will execute all queries from `samp.sql` threaded, and call no callback when finished (as you didn't specify one; it's optional).

**Comment by B3LlAT0R** [comment]
Thank you if i more problem i write again. Take care.

**Comment by B3LlAT0R** [comment]
i'm sorry i forgot, is safe use mysql_tquery_file for injection sql?
